stripe/stripe-node

.travis.yml, lib/StripeMethod.js, lib/StripeResource.js, lib/utils.js, test/resources/Account.spec.js, test/resources/ApplicationFeeRefunds.spec.js, test/resources/ApplicationFees.spec.js, test/resources/Balance.spec.js, test/resources/ChargeRefunds.spec.js, test/resources/Charges.spec.js, test/resources/Coupons.spec.js, test/resources/CustomerCards.spec.js, test/resources/CustomerSubscriptions.spec.js, test/resources/Customers.spec.js, test/resources/Events.spec.js, test/resources/FileUploads.spec.js, test/resources/InvoiceItems.spec.js, test/resources/Invoices.spec.js, test/resources/Plans.spec.js, test/resources/RecipientCards.spec.js, test/resources/Recipients.spec.js, test/resources/Tokens.spec.js, test/resources/Transfers.spec.js, test/testUtils.js, test/utils.spec.js
=> Add per-request options

lib/resources/Account.js, lib/resources/Accounts.js, lib/utils.js, test/resources/Account.spec.js
This adds support for accessing accounts via either the /v1/account or /v1/accounts endpoints.
r? @michelle 
CC @danwang
=> Add support for accounts resource

test/resources/BitcoinReceivers.spec.js, test/resources/Charges.spec.js
made bitcoin receiver creation in test consistent with backend (email is actually required)
r? @michelle
=> bitcoin receiver test consistency

lib/resources/Account.js, lib/stripe.js
=> Fix support for both stripe.account and stripe.accounts

lib/resources/Accounts.js, test/resources/Account.spec.js
No tests added but the bank account resources are required to use the new marketplace features.
I don't expect you to merge this PR as is, but keep in mind that a full support of the bank accounts would be great in a near future.
=> Add bank account support

.travis.yml, lib/Error.js, lib/StripeResource.js, test/Error.spec.js
I've also added 0.12 and iojs as test targets.
=> Add request IDs to all errors

lib/resources/Accounts.js, test/resources/Account.spec.js
=> Added the ability to delete an account

lib/resources/Disputes.js, lib/stripe.js, test/resources/Disputes.spec.js
r? @cupcait (not urgent, can wait til Monday) cc @michelle
=> Add top level disputes

lib/resources/Charges.js, lib/resources/Refunds.js, lib/stripe.js, test/resources/Refunds.spec.js
Will update to non-beta endpoint pre-merge, once the final endpoints go live.
r? @michelle 
cc @kyleconroy
=> Add top level refunds methods.

lib/resources/Orders.js, lib/resources/Products.js, lib/resources/SKUs.js, lib/stripe.js, test/resources/Orders.spec.js, test/resources/Products.spec.js, test/resources/SKUs.spec.js
=> Relay Resources

lib/Error.js, lib/StripeResource.js, test/Error.spec.js, test/stripe.spec.js
=> Add HTTP status code to errors.

lib/resources/FileUploads.js
may PR a linter... would help with stuff like this + styling consistency and so on
=> Remove lodash when required but not used

lib/MultipartDataGenerator.js, lib/StripeMethod.js, lib/StripeResource.js, lib/resources/Accounts.js, lib/resources/Invoices.js, lib/utils.js, test/flows.spec.js, test/resources/FileUploads.spec.js
=> Stick to single-quote string literals for consistency

lib/resources/Customers.js, test/resources/Customers.spec.js
=> Add the ability to verify a customer source

test/flows.spec.js, test/stripe.spec.js
=> Fix #219 Card expiration year is invalid

README.md, lib/resources/Products.js, lib/resources/SKUs.js, test/resources/Products.spec.js, test/resources/SKUs.spec.js
=> Support product and SKU deletion.

lib/resources/CountrySpecs.js, lib/stripe.js, test/resources/CountrySpecs.spec.js
r? @brandur 
The tests are really lacking here but other specs were as empty. Let me know if we should ensure that the data returned is valid.
=> Added support for the CountrySpec endpoint

README.md, lib/resources/Subscriptions.js, lib/stripe.js, test/resources/Subscriptions.spec.js
=> create sub resource supporting CRUDL and add tests

README.md, lib/resources/OrderReturns.js, lib/resources/Orders.js, lib/stripe.js, test/resources/OrderReturns.spec.js, test/resources/Orders.spec.js
r? @stripe/api-libraries 
cc @jimdanz
=> Support returning orders

CHANGELOG
=> Add explainer CHANGELOG

README.md, lib/resources/ThreeDSecure.js, lib/stripe.js, test/flows.spec.js, test/resources/ThreeDSecure.spec.js
r? @brandur 
cc @stripe/api-libraries @bct
Support for the new server-side 3D Secure API (currently in private beta).
=> Added support for 3D Secure

lib/resources/Sources.js, lib/stripe.js, package.json, test/resources/Sources.spec.js
This PR adds support for the Source API resource.
=> Add support for the Source resource

README.md, lib/resources/ApplePayDomains.js, lib/stripe.js, test/resources/ApplePayDomains.spec.js
=> Node bindings for ApplePayDomain

lib/StripeMethod.js
Hi,
this merge request fixes some minor issues.
It was created with help of [Feram][repo].
If it helped to improve this repository,
please consider to [star Feram's repo][repo] to show some love! 😊
PS:
The [Feram team][feramhq] is currently working on making this technology
available for everyone. If you want to be one of the first to use it,
please sign up up for the newsletter on [feram.co].
[repo]: https://github.com/feramhq/feram
[feramhq]: https://github.com/feramhq
[feram.co]: http://feram.co
=> Minor Fixes

README.md
Remedies documentation issue described in issue #282.
=> Create card before creating charge in example

lib/resources/ThreeDSecure.js, test/resources/ThreeDSecure.spec.js
cc @stripe/api-libraries @bct 
Adds a method for retrieving 3DS auths.
=> Adds 3DS retrieve endpoint

lib/resources/Sources.js, test/resources/Sources.spec.js
r? @will-stripe
Adds support for source update requests.
=> Adds update source endpoint

README.md, examples/webhook-signing/express.js, examples/webhook-signing/package.json, lib/Error.js, lib/Webhooks.js, lib/stripe.js, lib/utils.js, test/Webhook.spec.js, test/utils.spec.js
\o/
As the Node library doesn't have 'classes' and 'instances' of things, I'm not 100% sold that `constructEvent()` is the right name for the function here - though that's what it's set to for consistency.
I'm happy to discuss any pieces/parts of this, so let me know!
r? @ob-stripe 
cc @brandur-stripe
=> Add webhook signing

README.md, lib/StripeResource.js, lib/stripe.js, test/stripe.spec.js
I did a thing.  ¯\\\_(ツ)_/¯
r? @ob-stripe 
cc @brandur-stripe
=> Add `setAppInfo()`

lib/resources/Accounts.js, lib/resources/LoginLinks.js, lib/stripe.js, test/resources/Account.spec.js, test/resources/LoginLinks.spec.js
=> Add support for the login link resource

test/flows.spec.js, test/stripe.spec.js
This PR aims to use the new test tokens such as tok_visa instead or hardcoding raw PANs in the test suite.
=> Remove raw PANs from our test suite

examples/webhook-signing/express.js
Also I accidentally another couple of words.
=> `hte` is not a word

lib/Webhooks.js
=> Use utf8 to update HMAC payload

CHANGELOG.md
This way we can link into specific versions as needed.
(`sed` for the win \o/ )
=> Linkify changelog

.travis.yml
Start testing Node 9 in Travis.
=> Start testing Node 9

.gitignore, .travis.yml, README.md, package.json
Adds support for coveralls.io.
=> Add support for coveralls.io

lib/StripeResource.js
Sorry for missing this in #441
=> Fix indentation in StripeResource.js

.eslintrc.js, lib/Error.js, lib/StripeMethod.js, test/Webhook.spec.js, test/flows.spec.js, test/resources/ApplicationFeeRefunds.spec.js, test/resources/CustomerSubscriptions.spec.js
cc @stripe/api-libraries @kesla 
Enables the indentation rule in ESLint config, and fixes a few files with bad indent (by running `eslint . --fix`).
=> Enable indent linting rule

.travis.yml
Node 10 has been released, let's start testing it :)
=> Start testing Node 10 on Travis CI

lib/resources/PaymentIntents.js, lib/stripe.js, test/resources/PaymentIntents.spec.js
This feature is currently gated so the tests are stubbed for now.
r? @ob-stripe 
cc @jenan-stripe @michelle-stripe
=> Add support for the PaymentIntent resource

lib/ResourceNamespace.js, lib/resources/Issuing/Authorizations.js, lib/resources/Issuing/Cardholders.js, lib/resources/Issuing/Cards.js, lib/resources/Issuing/Disputes.js, lib/resources/Issuing/Transactions.js, lib/stripe.js, test/resources/Issuing/Authorization.spec.js, test/resources/Issuing/Cardholders.spec.js, test/resources/Issuing/Cards.spec.js, test/resources/Issuing/Disputes.spec.js, test/resources/Issuing/Transactions.spec.js, test/testUtils.js
=> Add Issuing API calls, create a 'StripeNamespace'

lib/resources/UsageRecordSummaries.js, lib/stripe.js, test/resources/UsageRecordSummaries.spec.js
=> Add support for usage record summaries

README.md
Coming from https://github.com/stripe/stripe-node/issues/296#issuecomment-432718356, I have adapted the [various](https://github.com/stripe/stripe-node/issues/296#issuecomment-335308245) [recommendations](https://github.com/stripe/stripe-node/issues/296#issuecomment-425801351) of @sampsonjoliver and others (thanks!).
Thanks also to everyone who has [contributed](https://github.com/DefinitelyTyped/DefinitelyTyped/commits/master/types/stripe/index.d.ts) to the Stripe DefinitelyTyped package. 
=> Clarify TypeScript usage

lib/resources/WebhookEndpoints.js, lib/stripe.js, test/resources/WebhookEndpoints.spec.js
=> Add support for the Webhook Endpoint resource

lib/StripeMethod.js, lib/resources/Orders.js, lib/resources/Products.js, lib/resources/SKUs.js
r? @rattrayalex-stripe @jlomas-stripe 
Fixes #514.
=> Fix `stripeMethod` documentation, remove `required` parameter

lib/resources/Invoices.js, test/resources/Invoices.spec.js
=> Add new methods for the Invoice resource

lib/resources/Radar/ValueListItems.js, lib/resources/Radar/ValueLists.js, lib/stripe.js, test/resources/Radar/ValueListItems.spec.js, test/resources/Radar/ValueLists.spec.js
=> Add support for Radar ValueList and ValueListItem resources

lib/resources/Reviews.js, lib/stripe.js, test/resources/Reviews.spec.js
=> Add support for the Review resource

lib/resources/AccountLinks.js, lib/stripe.js, test/resources/AccountLinks.spec.js
=> Add support for the Account Link resource

lib/resources/CheckoutSessions.js, lib/stripe.js, test/resources/CheckoutSessions.spec.js
=> Add support for the Checkout Session resource

lib/resources/PaymentMethods.js, lib/stripe.js, test/resources/PaymentMethods.spec.js
=> Add support for the PaymentMethod resource

lib/resources/CreditNotes.js, lib/stripe.js, test/resources/CreditNotes.spec.js
=> Add support for CreditNote

lib/resources/Invoices.js, test/resources/Invoices.spec.js
Fixes https://github.com/stripe/stripe-node/issues/591
r? @ob-stripe @rattrayalex-stripe 
=> retrieveUpcoming on Invoice can now take one hash as parameter

lib/resources/TaxRates.js, lib/stripe.js, test/resources/TaxRates.spec.js
=> Add support for the TaxRate resource and APIs

.editorconfig, .vscode/extensions.json, .vscode/settings.json
=> Add VSCode and EditorConfig files

lib/resources/Accounts.js, lib/resources/Capabilities.js, lib/stripe.js, test/resources/Account.spec.js, test/resources/Capabilities.spec.js
=> Add support for the Capability resource and APIs

lib/resources/Invoices.js
r? @paulasjes-stripe @rattrayalex-stripe 
Fixes #630.
=> Make autopagination functions work for `listLineItems` and `listUpcomingLineItems`

lib/StripeMethod.js, lib/StripeResource.js, lib/stripe.js
Attempt 2, created a new branch as the old one was based off of `v7.0.0` and would have been a pain to detangle.
Leaning pretty hard on the tests here, which all pass in Node v6.
r? @rattrayalex-stripe @ob-stripe
=> Remove most instances of 'self' in favor of arrow functions

lib/resources/Customers.js, test/resources/Customers.spec.js
=> Add support for Customer Balance Transaction resource and APIs

lib/resources/Customers.js
r? @ob-stripe 
cc @remi-stripe 
Should be a noop for users, just a reshuffle to match codegen.
=> Reorder customer methods for codegen

lib/resources/BalanceTransactions.js, lib/resources/Customers.js, test/resources/BalanceTransactions.spec.js
r? @ob-stripe @rattrayalex-stripe 
=> Move Balance History to /v1/balance_transactions

lib/resources/SubscriptionSchedules.js, test/resources/SubscriptionSchedule.spec.js
=> [codegen] Remove subscription schedule revisions 

lib/resources/SubscriptionItems.js, test/resources/SubscriptionItems.spec.js
r? @rattrayalex-stripe (feel free to change reviewer)
=> [codegen] Add `subscriptionItems.createUsageRecord()` method

lib/resources.js, lib/resources/Mandates.js, test/resources/Mandates.spec.js
=> Add support for `Mandate`

package.json, yarn.lock
This will unlock better reporting from our internal CI.
=> Add junit reporter dev dependency

lib/resources/CreditNotes.js, test/resources/CreditNotes.spec.js
Codegen for openapi ab6898a
r? @ob-stripe 
=> Add support for CreditNote preview

README.md, lib/StripeResource.js, lib/autoPagination.js, lib/stripe.js, test/autoPagination.spec.js, types/Webhooks.d.ts, types/lib.d.ts
=> Small typo fixes

README.md
One of the example is a bit more convoluted than before unfortunately but I think it still works
r? @ob-stripe 
=> Remove charge mention from examples

types/2019-12-03/Customers.d.ts, types/2019-12-03/Invoices.d.ts, types/2019-12-03/SourceTransactions.d.ts, types/2019-12-03/TaxIds.d.ts
Codegen for openapi 8be50d1
r? @ob-stripe 
=> Add new type for `TaxId` and `sender_account_name` on `SourceTransaction`

README.md
r? @ob-stripe 
cc @edwin-stripe
=> Small grammatical fixes to the readme

package.json, yarn.lock
Fixes https://github.com/stripe/stripe-node/issues/783
cc @SimonSchick thanks for reporting!
=> Allow @types/node 8.1

types/2019-12-03/Customers.d.ts, types/2019-12-03/Invoices.d.ts, types/2019-12-03/TaxIds.d.ts
=> Add new type of `TaxId`

types/2019-12-03/Files.d.ts, types/2019-12-03/PaymentIntents.d.ts, types/2019-12-03/Subscriptions.d.ts
Multiple new features:
* Add new `purpose` for `File`: `additional_verification`
* Add `error_on_requires_action` as a parameter for `PaymentIntent` creation and confirmation
Codegen for openapi fd14b44
r? @ob-stripe 
=> Multiple API changes

types/2019-12-03/Issuing/Disputes.d.ts
Codegen for openapi 40a20cd
r? @ob-stripe 
=> Add new enum values in `reason` for Issuing `Dispute` creation

types/2019-12-03/AccountLinks.d.ts, types/2019-12-03/Charges.d.ts, types/2019-12-03/SubscriptionItems.d.ts, types/2019-12-03/Subscriptions.d.ts, types/2019-12-03/Transfers.d.ts
Codegen for openapi 5ecc185
Fixes #817
=> Make `type` on `AccountLink` an enum

types/2019-12-03/Customers.d.ts, types/2019-12-03/Invoices.d.ts, types/2019-12-03/TaxIds.d.ts
=> Add `my_sst` as a valid value for `type` on `TaxId`

types/2020-03-02/WebhookEndpoints.d.ts
Codegen for openapi 23ae7d8
r? @ob-stripe 
=> Add support for `metadata` on `WebhookEndpoint`

types/2020-03-02/Checkout/Sessions.d.ts, types/2020-03-02/Issuing/Authorizations.d.ts, types/2020-03-02/Issuing/Cardholders.d.ts, types/2020-03-02/Issuing/Cards.d.ts
Codegen for openapi c9f5f4f
r? @ob-stripe 
=> Multiple API changes for Issuing resources

CHANGELOG.md
=> Fix changelog with more details

.vscode/settings.json, examples/webhook-signing/typescript-node-express/express-ts.ts, test/StripeResource.spec.js, test/resources/Plans.spec.js, types/test/typescriptTest.ts, yarn.lock
Run `yarn upgrade` and reformat  a few files to be compliant with ESLint rules.
=> Run `yarn upgrade` and additional cleanup

types/2020-03-02/Checkout/Sessions.d.ts
=> Add support for `payment_intent_data[transfer_group]` on Checkout `Session`

types/2020-03-02/PaymentIntents.d.ts, types/2020-03-02/PaymentMethods.d.ts
=> Add support for `payment_method_data` on `PaymentIntent`

test/resources/Plans.spec.js, test/resources/Prices.spec.js
Fixes https://github.com/stripe/stripe-node/issues/916#issuecomment-650627126
r? @remi-stripe (self-approving, just a test change)
=> Fix tests for `Plan` and `Price` to not appear as amount can be updated.

types/2020-03-02/AccountLinks.d.ts, types/2020-03-02/Charges.d.ts
=> Add support for `account_onboarding` and `account_update' as `type` on `AccountLink`

types/2020-03-02/Checkout/Sessions.d.ts, types/2020-03-02/CreditNotes.d.ts
=> Improve types for `customer` on `CreditNote` to support `DeletedCustomer`

test/resources/Customers.spec.js
Fix the broken tests reported in https://github.com/stripe/stripe-node/issues/974
=> Fix createSource tests

types/2020-03-02/Checkout/Sessions.d.ts
=> Add support for Alipay on Checkout `Session`

types/2020-08-27/Checkout/Sessions.d.ts
Codegen for openapi cca1662
r? @suz-stripe 
=> Add support for SEPA debit on Checkout

types/2020-08-27/Accounts.d.ts
=> Add support for `tos_acceptance[service_agreement]` on `Account`

lib/resources/Payouts.js, test/resources/Payouts.spec.js, types/2020-08-27/Payouts.d.ts
=> Add support for the Payout Reverse API

types/2020-08-27/PaymentIntents.d.ts, types/2020-08-27/PaymentMethods.d.ts
=> Add support for passing `p24[bank]` for P24 on `PaymentIntent` or `PaymentMethod`

types/2020-08-27/Accounts.d.ts, types/2020-08-27/Invoices.d.ts, types/2020-08-27/Tokens.d.ts
=> Add support for `company[registration_number]` on `Account`

types/2020-08-27/Accounts.d.ts
=> Add support for `capabilities[grabpay_payments]` on `Account`

README.md
promises example wasn't working, fixed it. Now creates a customer with the customer id and sends invoice.
=> fixed promises example

lib/autoPagination.js
fix few typos in `autoPagination.js`
=> typo receieved -> received

README.md
=> Add link to YouTube playlist from readme

.github/workflows/main.yml
r? @ob-stripe
Runs `yarn test` in github actions. `yarn test` triggers eslint, typescript, and mocha.
=> CI: Github Actions

types/Errors.d.ts
=> types: export StripeRawError type

types/2020-08-27/Accounts.d.ts, types/2020-08-27/Capabilities.d.ts, types/2020-08-27/Checkout/Sessions.d.ts, types/2020-08-27/Persons.d.ts
Codegen for openapi edc4cae.
* `Capability.requirements.errors[].code`, `Account.requirements.errors[].code` and `Person.requirements.errors[].code` added new enum members: `verification_missing_owners, verification_missing_executives and verification_requires_additional_memorandum_of_associations`
* `SessionCreateParams.locale` and `CheckoutSession.locale` added new enum members: `th`
=> API Updates

types/2020-08-27/Checkout/Sessions.d.ts, types/2020-08-27/Mandates.d.ts, types/2020-08-27/PaymentIntents.d.ts, types/2020-08-27/SetupIntents.d.ts
=> fix typo parmeter -> parameter

test/resources/GeneratedTests.spec.js
Adds auto-generated test suite. This test suite tries to invoke each Stripe method (excluding a small subset) against stripe-mock.
=> Add auto-generated test suite.

lib/net/NodeHttpClient.js
=> Typo in NodeHttpClient comment

README.md
=> Update beta EOL date.

package.json, yarn.lock
Bump `qs` dependency to latest version.
=> Bump qs package to latest.

.github/workflows/main.yml
Adds an automatic NPM publishing step.
=> Add node release action

.github/workflows/main.yml
I verified the the script works. Switch condition to trigger on pushed tags.
=> Turn on automatic publishing

.github/workflows/main.yml
Update coveralls step to run for one node version, remove finish step.
Relates to https://github.com/stripe/stripe-php/pull/1360#discussion_r955290668
=> Update coveralls step to run for one node version, remove finish step

.github/workflows/main.yml, README.md, package.json
Update supported runtime versions for next major release. The changes include:
* Update README to indicate support for Node 12 and above
* Remove Node 10 from test matrix
* Update engines field to indicate support for runtime versions >= 12
=> Update supported runtime versions

src/Types.d.ts, types/lib.d.ts, types/test/typescriptTest.ts
We removed the feature itself in the major.
=> Remove BASIC_METHODS from TS definitions

types/index.d.ts
Instead of generating the entire file only replace sections of it with autogenerated code.
=> Generate sections of types/index.d.ts

examples/webhook-signing/nextjs/pages/api/webhooks.ts
Fixes https://github.com/stripe/stripe-node/issues/1756
=> Use correct environment variable

.gitignore, testProjects/cloudflare-pages/package.json
The test has started leaving around a `_worker.bundle` file for me locally. Update the build script to remove all build artifacts after testing.
=> Update cloudflare-pages test project build

CHANGELOG.md
Fixes https://github.com/stripe/stripe-node/issues/1847
=> Changelog: `CheckoutSessionCreateParams` -> `Checkout.SessionCreateParams`

CHANGELOG.md, src/net/NodeHttpClient.ts, test/StripeResource.spec.ts, tsconfig.cjs.json
Needed to include the revert #1859 before releasing the beta.
=> Merge master into beta

test/resources/Subscriptions.spec.js
This method is being removed in the next v13 major version.
=> Remove subscriptions.del test

examples/webhook-signing/express/main.ts, examples/webhook-signing/koa/main.ts, examples/webhook-signing/nextjs/pages/api/webhooks.ts, examples/webhook-signing/test/main.ts, testProjects/cloudflare-pages/functions/index.js, testProjects/mjs-ts/index.ts, types/lib.d.ts, types/test/typescriptTest.ts
=> Update Typescript for the new API Version

.github/workflows/main.yml
Similar to https://github.com/stripe/stripe-php/pull/1624
=> Use GITHUB_OUTPUT instead of deprecated ::set-output

src/RequestSender.ts, test/stripe.spec.ts
Analogous to https://github.com/stripe/stripe-python/pull/1191
=> Beta: report `raw_request` usage

types/Issuing/AuthorizationsResource.d.ts
* Cleaned up deprecation message in docstrings.
=> Removed deprecation message description

src/RequestSender.ts, src/Types.d.ts
as a follow up to https://github.com/stripe/stripe-node/pull/2172, some were missed in the beta branch
=> Fix additional null types

CHANGELOG.md
Removed entries for some clean up PRs we pushed
Removed entry for rawrequest which was already covered
=> Remove entries for the follow ups from CHANGELOG.md

justfile, types/apiVersion.d.ts, types/lib.d.ts, types/test/typescriptTest.ts
* Ran `just merge node-private-preview` and fixed merge conflicts
* Manually updated new `apiVersion.d.ts` file.
=> Merge node-private-preview

.github/workflows/main.yml, CHANGELOG.md, README.md
- ran `just merge node-private-preview` and committed the results
=> Merge to private-preview
