stripe/stripe-node

lib/resources/FileUploads.js, test/resources/FileUploads.spec.js
This allows the node bindings to be able to list file uploads.
r? @SlexAxton
=> Add functionality for listing file uploads.

lib/resources/Accounts.js, test/resources/Account.spec.js
If a parameter is passed to Retrieve customer that isn't an
auth key, the library incorrectly assumed it was a account id.
Updated the check to ensure that a function could be passed in as
a sole argument and it would retrieve the account for the pre-set
api key.
Fixes #147
=> Check if a callback is passed to Retrieve Customer

CHANGELOG, README.md, lib/resources/ApplicationFeeRefunds.js, lib/resources/ChargeRefunds.js, lib/resources/CustomerCards.js, lib/resources/CustomerSubscriptions.js, lib/resources/RecipientCards.js, lib/resources/TransferReversals.js, lib/resources/Transfers.js, lib/stripe.js, package.json, test/resources/TransferReversals.spec.js, test/resources/Transfers.spec.js
r? @michelle @bkrausz @SlexAxton 
Support CRUD of transfer reversal objects, and update `cancel` to use `/reversals` endpoint.
=> Support transfer reversals

README.md
The only place I could find this info before was on [this one page](https://stripe.com/docs/connect/payments-fees) of the docs, pointed out to me in IRC. Figured the README was a much better place for it.
=> Add info on how to use the Stripe-Account header

README.md, lib/resources/Invoices.js, test/resources/Invoices.spec.js
The Upcoming Invoice API now supports a ton of cool optional params
to help calculate prorations.
Since the customer ID is still required, and the subscription id is
optional, the second parameter to the retrieveUpcoming endpoint
can be an options object or a string (string must be the subscription
id for legacy compatibility).
Fixes #176
=> Allow an options hash to be passed in to Upcoming Invoice API

lib/utils.js, package.json, test/utils.spec.js
Fixes a bug where arrays of hashes do not work properly. Also `a[]=first&a[]=second` is more commonly used than `a=first&a=second`.
r? @michelle
=> Switch array rendering syntax to brackets

lib/StripeResource.js
It is a problem for fileUploads since the utils#stringifyRequestData can't handle binary files. If the resource has a requestDataProcessor, it should send the original unprocessed data. Since the variable requestData is being declared twice, I assume someone forgot to erase this line.
With the line there, the following error happens on fileUploads (binary files):
/node_modules/stripe/node_modules/qs/lib/stringify.js:40
URIError: URI malformed
at encodeURIComponent (native)
at Object.internals.stringify (/Users/gabrielmarques/Desktop/CareLuLu/v2/CareLuLu/node_modules/stripe/node_modules/qs/lib/stringify.js:40:52)
at Object.internals.stringify (/node_modules/stripe/node_modules/qs/lib/stringify.js:56:46)
at Object.module.exports [as stringify] …
=> Send original data to requestDataProcessor if available.

README.md
Add description for `customers.retrieveSubscription` method, which was missing.
=> Add missing method to README

lib/resources/Accounts.js, test/resources/Account.spec.js
Old (pre-prefix) account ids and api keys are hard to differentiate. As
such old account ids would pass the `isAuthKey` tried to identify
whether a user was requesting a connected account or if they were trying
to request the account for the passed api key.
This is a "major" change in that an api key cannot be passed as a string
to the first argument. It can be passed in the options parameter as the
`api_key` value, or as a string if the user passes `null` as the account
id.
[stripe/stripe-node#194]
=> Remove ability for API keys to be passed as 1st param to acct.retrieve

lib/Error.js, test/flows.spec.js
For consistency, lets rename all errors to end in Error.
closes #159
=> Rename StripeInvalidRequest to StripeInvalidRequestError

lib/stripe.js
In order to be able to stub the library sinonjs needs an property to stub:
> https://github.com/sinonjs/sinon/issues/664
> https://github.com/sinonjs/sinon/issues/664#issuecomment-71980876
After that it would be possible to do:
```
var stripe = require('stripe');
var stubStripe = sinon.stub(stripe, 'Stripe').returns(stubStripeClient);
```
=> Add Stripe exports for easier mocking

lib/StripeMethod.js, test/resources/Charges.spec.js
Return usage errors through callbacks as described in #215. This has the advantage of never throwing an error unexpectedly in user code.
@kyleconroy Would you mind taking a review pass on this? I literally learned how promises work 45 seconds ago. Thanks!
=> Return usage errors through callback

lib/resources/Accounts.js, test/resources/Account.spec.js
Corresponding to the [Account.reject API method](https://stripe.com/docs/api/node#reject_account).
r? @stripe/api-libraries
=> Add Account.reject method.

lib/utils.js
makeURLInterpolator requires use of eval to create a function which interpolates url strings in constant time.
By taking a small increase in interpolator complexity to linear time with respect to parts interpolated, we can improve the security of stripe-node. This also helps this package conform to security requirements an electron application might have.
=> Remove eval from url interpolator

package.json
Bumps some dependencies including putting lodash onto a 4.x.x series.
Fixes #242.
=> Update dependencies; bump lodash to 4.x.x series

README.md
Received some feedback from fieldeng that info/documentation on passing options isn't easily discoverable. Added a link to the README to the wiki page for Passing Options. 
r? @rasmusrygaard 
=> Updated README with link to Passing Options wiki page

lib/stripe.js, test/stripe.spec.js
URI-encodes all fields of the JSON version of the Stripe User-Agent
field in case something like the system `uname` contains a special
character.
Fixes #246.
r? @dpetrovics Mind taking a look at this?
=> URI-encode all fields of User-Agent

lib/StripeMethod.basic.js, lib/StripeMethod.js, lib/StripeResource.js, test/resources/Customers.spec.js, test/stripe.spec.js
`Promise.defer` from Bluebird is considered deprecated [1]. Here we
remove its uses and replace them with `Promise.new`.
It would be nice to find a reviewer for this one who is somewhat familiar with
the Node/Bluebird idioms. If anyone wants to volunteer, that would be amazing,
otherwise I'll try and track someone down.
Fixes #257.
[1] http://bluebirdjs.com/docs/deprecated-apis.html#promise-resolution
=> Remove uses of `Promise.defer`

README.md
Small typo: you don't pass a `chargeId` to retrieve/delete an Apple Pay domain.
r? @brandur
=> Update README for retrieving/deleting Apple Pay domains

lib/resources/SubscriptionItems.js, lib/stripe.js, test/resources/SubscriptionItems.spec.js
Add SubscriptionItem object to support list, retrieve, create, update, deletion on subscriptions items through `v1/subscription_items`. Note that documentation for this endpoint in the README has yet to be filled out since this feature is still in development.
=> Add SubscriptionItem object

lib/MultipartDataGenerator.js, lib/StripeMethod.basic.js, lib/StripeMethod.js, lib/StripeResource.js, lib/utils.js, package.json, test/utils.spec.js
Lodash is being used in relatively few places and as described in #259
can cause some problems in transforming objects to versions that cannot
be properly encoded.
Here we remove Lodash. Much of its functionality has been added to ES6
anyway, so we can eventually even remove some of the vendored functions
that we have.
Fixes a report received in #259.
=> Remove Lodash dependency

README.md, package.json
Adds a section in the README like some of our other languages for
running either a single file of tests or a single test within a file. A
script is also added to `package.json` to support this.
Slightly unfortunate: the `--grep` flag of Mocha is case sensitive which
will probably lead to confusion because we use a lot of inconsistent
casing in test names. There is a case insensitive version in modern
version of Mocha, but we'll have to upgrade to 3.0.0+ to get it.
=> Add instructions for running single tests

README.md
This adds the refunds resource to the README and removes the old
`refund` helper from charge (which is now deprecated in favor of the
resource).
Fixes #280.
=> Add refunds resources

README.md
I think setup with secret API key should be separated in docs.
Also I've added those customer's sources related methods I didn't find in your README first.
=> Docs improvements sources

README.md
correct usage is `stripe.accounts.*`
=> typo `account` -> `accounts`

lib/resources/Sources.js, test/resources/Sources.spec.js
r? @will-stripe
cc @stripe/api-libraries @stan-stripe
This PR adds support for the `/verify` endpoint for sources, for use with ACH debit and other source types that require a verification.
=> Adds support for verify source endpoint

.gitignore
Dug into this issue, and it looks like NPM defaults to "include everything" even if `tags` would be excluded, for example, by a global `.gitignore` rule.
https://docs.npmjs.com/misc/developers
=> Ignore `tags` file for NPM, fixes #302

README.md
There is no information about how to use node sdk behind the proxy, tho it was implemented a while ago.  Please consider adding this to the readme, might save someone an hour or two
=> Added proxy configuration to README.md

README.md
I replaced the Travis badge with its vector version in the README, and added badges for npm version, npm downloads, and trying the package live in RunKit.
=> Add README badges (npm & RunKit) and update Travis

lib/StripeResource.js, test/stripe.spec.js
Makes access to `Request-Id` easier for non-error responses. So for
example:
``` node
stripe.balance.retrieve({
stripe_account: "acct_foo"
}).then(function(balance) {
console.log(balance.lastResponse.requestId);
})
```
Fixes #315.
r? @ob-stripe
=> Make Request-Id easily available on `lastResponse`

README.md
Adds a section that includes some basic information on looking at
response information.
Requested on #315.
r? @ob-stripe 
@stripe/api-libraries
=> Add section "Examining Responses"

README.md
=> Switch API docs link from `/python` to `/node`

lib/StripeResource.js
This was erroneously given a bad reference in #316. See #315 for details.
=> Fix error requestId reference

lib/resources/Payouts.js, lib/stripe.js, test/resources/Payouts.spec.js
The Transfer object used to represent all movements of funds in Stripe. It split in three resources:
- Transfer: this describes the movement of funds between Stripe accounts and is specific to Stripe Connect.
- Payout: this describes the movement of funds from a Stripe account to a bank account, debit card or any future payout method.
- RecipientTransfer: this describes the movement of funds from a Stripe account to a Recipient's card or Bank Account. This is here for legacy reasons and can only be accessed from an expanded BalanceTransaction.
This change is behind an API version so old API versions would still use the Transfer object for everything while new API version would see the split.
This applies beyond the new object as some properties/methods are removed from Transfer and other …
=> Added support for the new Payout and RecipientTransfer objects

lib/StripeMethod.js, lib/StripeResource.js, test/StripeResource.spec.js
Improve the error message when a `stripeMethod` is called but a
parameter is accidentally ommitted. Previously, we were accidentally
including the product of `utils.makeURLInterpolator` in the error
string, which made it very difficult to read:
```
Error: Stripe: Argument "id" required, but got: undefined (on API request to GET function (outputs) {
return cleanString.replace(/\{([\s\S]+?)\}/g, function($0, $1) {
return encodeURIComponent(outputs[$1] || '');
});
})
at Object.<anonymous> (/Users/brandur/stripe/stripe-node/lib/StripeMethod.js:53:21)
```
I think this was basically an implementation accident, as what it's
actually trying to do is print the path of the API call that's about to
be invoked. We now produce this instead:
```
Error: Stripe: Argument "id" required, but got: undefined …
```
=> Improve error message when ommitting a parameter

lib/StripeMethod.js, test/resources/Charges.spec.js
If you accidentally do `stripe.charges.capture(chargeObject)` instead of `stripe.charges.capture(chargeObject.id)`, you currently get this error back from Stripe:
```
{ 
"type": "invalid_request_error", 
"message": "No such charge: [object Object]", 
"param": "id", 
"statusCode": 404, 
"requestId": "req_ABC123xyz" 
}
```
It would be better if you got something like this before the API call was even made:
```
Unhandled rejection Error: Stripe: "id" must be a string, but got: object (on API request to `POST /charges/{id}/refund`)
```
So ... that's what this does.  ¯\\\_(ツ)_/¯
=> Check to make sure the `id` is a String

lib/utils.js
Some JavaScript environments incorrectly expose `prototype` in the `Object.hasOwnProperty()` method. The `protoExtend()` function should handle this.
=> Check if object property isPrototype before adding it to Constructor.

lib/Error.js, lib/StripeResource.js, test/Error.spec.js
It can't hurt to have these accessible when handling an error. We
already have a few other pieces of response information like request ID
and status code, so it's fairly conventional.
Fixes #335.
r? @jlomas-stripe
=> Make response headers accessible on errors

README.md
* In the *Writing a Plugin* section, `MyAwesomePlugin` should be a string, not a variable name.
* In the *Configuring for Connect* section, the `stripe_account` property should use single quotes, as all other strings in the examples do.
=> Fix two small typos in Readme

examples/webhook-signing/express.js
Fixes #341 where `body-parser` was conflicting with other instances of `body-parser` in the app.  Replaced it with a middleware function that accomplishes the same thing.
=> Remove `body-parser` from the Express webhook signing example

lib/utils.js
Fixes utils.isOptionsHash() TypeError: o.hasOwnProperty is not a function.
```
TypeError: o.hasOwnProperty is not a function
at ./node_modules/stripe/lib/utils.js:19:16
at Array.some (native)
at Object.isOptionsHash (./node_modules/stripe/lib/utils.js:18:81)
at Object.getDataFromArgs (./node_modules/stripe/lib/utils.js:59:44)
at Object.<anonymous> (./node_modules/stripe/lib/StripeMethod.js:75:31)
```
=> fixes #352 isOptionsHash - TypeError

lib/resources/Invoices.js, test/resources/Invoices.spec.js
Given the following: 
```
stripe.invoices.retrieveUpcoming(customerId, {
subscription: subscriptionId,
subscription_items: [
{
id: itemToDelete,
deleted: true
},
{
plan: 'something-1'
},
{
plan: 'something-2'
}
],
subscription_prorate: true
});
```
The result would only contain one new plan - specifically, `something-2`, because the API can't find the boundary there.
This PR makes use of the same thing that was [used in `Subscription.update`](https://github.com/stripe/stripe-node/blob/bd4bd44975d4427aad60a488e959f10677f396e9/lib/resources/Subscriptions.js#L28) to make sure the arrays get converted into indexed objects.
=> Add utils.arrayToObject() to retrieveUpcoming() for `subscription_items`

test/resources/Invoices.spec.js
cc @stripe/api-libraries @ark-stripe
Users can now provide a `source` parameter when paying invoices. The Node library actually already supports this, I just updated the test to make sure that sending parameters is supported.
=> Add parameters when calling `pay` on an invoice

lib/utils.js
The tests are currently failing on node v4 and versions prior to v4.5.x due to a mismatch in the **Buffer.from** API. This was fixed in https://github.com/nodejs/node/pull/7562 and backported to v4.5.x. PR fixes the current use of the function by handling the **TypeError** being thrown.
Alternative solutions:
- Exclude the failing node versions in package.json
- Use semver checking to use the correct API instead of handling the exception
=> Handle Buffer.from TypeError on node versions prior to 4.5.x

test/flows.spec.js, test/stripe.spec.js, test/testUtils.js
A [test just popped](https://travis-ci.org/stripe/stripe-node/jobs/262392702) because we are using timestamps as our 'random string suffix' and ... the tests happened in the same second.
This just switches those all from a timestamp to a random string.
=> Switch from using timestamps to a random string in tests

README.md, lib/StripeResource.js, lib/stripe.js, lib/utils.js, test/flows.spec.js, test/utils.spec.js
Still need to add docs; I can't get `jscs` to run without 💥 for some reason, so ... I'm making Travis-CI run my linting.  ¯\\\_(ツ)_/¯
=> Add `request` and `response` events to Stripe object

test/flows.spec.js
_My tests were bad and I should feel bad._
I was sending `api_version` in the header, instead of `stripe_version`, so it ... wasn't actually setting them.
Couldn't understand why the versions needed updating in #371 but after investigating I realized it's because I wasn't _actually_ specifying them, and `latest` no longer mapped to the value I was using.
=> Fix request headers in tests

lib/StripeResource.js, lib/stripe.js, test/StripeResource.spec.js, test/stripe.spec.js
Use Bearer auth instead of Basic auth to authenticate with the API.
I don't have much experience working with Node so it's possible what I've written isn't very idiomatic.
=> Use Bearer auth

.npmrc
npm 5 creates a `package-lock.json` and recommends commiting it to the the repo. When present, the lock file is used instead of `package.json`.
This makes sense for apps, but not for libraries like stripe-node. This PR adds a `.npmrc` config file so that npm will not create `package-lock.json` files.
=> Prevent package-lock.json files from being created

lib/StripeMethod.js, lib/StripeResource.js, lib/stripe.js, lib/utils.js, package.json
The [`object-assign`](https://www.npmjs.com/package/object-assign) package is only useful for code targeting Node < 4. Since this is no longer the case for stripe-node, we can safely get rid of it and call `Object.assign` directly.
=> Remove object-assign package

README.md
Updates the sample request in the README file to use the `tok_visa` test token rather than the raw test PAN.
=> Use test token rather than raw test PAN

package.json, test/flows.spec.js
While working on #383, I noticed that npm was complaining about some deprecated packages, so I thought I'd just bump all dependencies to their latest versions. Should probably have done this at the same time as #382, sorry!
I had to modify some tests to account for a breaking change in chai 4.x (cf. https://github.com/chaijs/chai/issues/781).
=> Bump dependencies versions

.travis.yml
Starts testing Node 4.0.0.
Currently the earliest version we're testing is `4`, which Travis interprets as "latest 4.x release". Since we want to support all >= 4.0.0 versions, we should also explicitly test Node 4.0.0.
=> Start testing Node 4.0.0

lib/MultipartDataGenerator.js, lib/utils.js, package.json
ESLint recommends using the `safe-buffer` package for Node <= 4.5, and it also lets us get rid of some code that we added to manually handle this (cf. #365).
Let's wait until #387 is merged and this PR is rebased to make sure everything's still working as expected!
=> Use safe-buffer package

lib/StripeMethod.js, lib/utils.js, test/utils.spec.js
If you include any of `stripe_account`, `api_key` or `idempotency_key` in the `data` object, that object will be treated as the `options` object and so only the options will be processed - i.e., the data will be discarded.
With this change, the first argument object will be stripped of the `options` keys and returned, allowing for both `data` and `options` to come from the same object.
Also added some Charge creation tests to ensure that this works - at least in terms of adding a `Stripe-Account` header.
=> Throw an error if options are provided inside the data argument

lib/utils.js, test/utils.spec.js
Fixes #393.  The initial change (#306) didn't properly handle the case where the object was all `options` - it was `console.warn`ing in that case - but now it handles it properly.
=> Fix the comparison for the args/options warnings

README.md, lib/Webhooks.js
Since this is something that comes up a lot, I thought it might be worth calling it out a bit more explicitly, both in the Readme and in the Error we return when the signatures don't match.
=> More explicitly call out that `constructEvent` needs the raw body

CHANGELOG
We initially had this in place so that old links would still have
somewhere to point to, but I think it's been long enough at this point
(we've shipped *many* releases with the proper link since then). Worst
case scenario is that people just go up to the repository and find
`CHANGELOG.md` manually.
=> Remove old CHANGELOG

.eslintrc.js, .jscsrc, examples/webhook-signing/.eslintrc.js, examples/webhook-signing/express.js, lib/StripeMethod.js, lib/utils.js, package.json, test/.eslintrc.js, test/resources/Customers.spec.js, test/stripe.spec.js, test/testUtils.js, test/utils.spec.js
This PR is an attempt at fixing #367. It replaces jscs with ESLint.
The main problem is that we were using a custom ruleset for jscs (https://github.com/stripe/javascript-style), which I think is going to be difficult to port to ESLint.
What I did in this PR is use `eslint --init` to create a new configuration file from scratch. ESLint can scan existing code to write a configuration file that more or less matches the style in the current code.
After doing so, there were still ~70 linting errors which I fixed manually. Most of them were legitimate errors (unused variables, unnecessary semicolons), a few were style errors but they were sensible so I fixed them as well.
I'm not sure if this is how we want to handle the switch to ESLint. I'm not a fan of the very long custom configuration …
=> Use ESLint instead of jscs

CHANGELOG.md
Reformats the changelog a little bit so that it looks identical to the format we're using in four other Stripe languages now.
[Link to a rendered version of the changelog](https://github.com/stripe/stripe-node/blob/brandur-reformat-changelog/CHANGELOG.md).
=> Reformat the changelog for uniformity

lib/resources/Sources.js, test/resources/Sources.spec.js
cc @stripe/api-libraries @stan-stripe
Adds support for the `/v1/sources/src_.../source_transactions` endpoint.
=> Add support for listing source_transactions

lib/resources/ExchangeRates.js, lib/stripe.js, test/resources/ExchangeRates.spec.js
cc @stripe/api-libraries @alixander-stripe
Adds support for the new `/v1/exchange_rates` endpoints.
=> Add ExchangeRates API methods

README.md
Now that Node 8 is LTS, it might be nice to show `await` syntax first  (here's some [reasoning](https://gist.github.com/mikermcneil/c1028d000cc0cc8bce995a2a82b29245) on that)
=> Update docs to take advantage of Node 8's `await`

test/flows.spec.js, test/resources/Products.spec.js
Version 2018-02-05 came with a major change to plans and products:
* Products now have a `type` which is `service` or `good`.
* Plans have `name` change to `nickname`.
* Plans now take a product (of `type=service`) on creation.
Testing on `master` is currently broken. This patch updates some test suites to
allow for the new API changes and fixes the suite.
r? @ob-stripe
=> Update subscriptions tests to pass with new API changes

test/flows.spec.js
As we're actively deprecating the old and undocumented /v1/3d_secure endpoint, we need to remove the test so that the test suite does not break.
r? @ob-stripe 
=> Remove old 3DS test to ensure test suite keep working

lib/resources/Topups.js, lib/stripe.js, test/resources/Topups.spec.js
This add standard retrieve, create and update client support for the new `/v1/topups` endpoint.
=> Add support for /v1/topups endpoints

README.md
The ES modules usage fails to compile in TS, so this should help TS users get started.
=> Add TypeScript usage to README

.eslintrc.js, lib/StripeMethod.basic.js, lib/StripeMethod.js, package.json, test/flows.spec.js, test/resources/Customers.spec.js, test/stripe.spec.js
cc @stripe/api-libraries @OrKoN
- Use native ES6 promises instead of Bluebird promises
- ~Add a `setPromise` configuration option for users to provide their own `Promise` implementation~
Fixes #438.
=> Use native promises

lib/StripeResource.js
pathWithSymbols may be undefined and then an exception is thrown from the path.join method.
bug details: #436
=> fix invalid path join #436

lib/StripeResource.js
When using a custom http agent and keepAlive is set the request won't create new sockets, meaning that the `'connect'` or `'secureConnect'` events won't run.
This fixes that.
=> Support custom agent with keepAlive: true

lib/resources/UsageRecords.js, lib/stripe.js, test/resources/Plans.spec.js, test/resources/UsageRecords.spec.js
Implement support for flexible billing options on plans and creating usage records.
=> Flexible/Metered Billing API support

lib/resources/IssuerFraudRecords.js, lib/stripe.js, test/resources/IssuerFraudRecords.spec.js
need to wait for update to stripe mock
=> Add support for v1/issuer_fraud_records endpoint

lib/resources/UsageRecords.js, test/resources/UsageRecords.spec.js
Makes sure that all of the elements of the original `arguments` array - with the first one being modified to extract and remove the SubscriptionItem ID - are passed through to the `stripeMethod()` call.
Fixes #451.
=> Fix UsageRecords so it passes through the rest of the arguments

lib/utils.js, test/utils.spec.js
I.e., "Do the thing I said I'd do in #375".
I also fixed some tests that weren't running properly (because they were async but didn't include a `done`), and I'm ... also not sure that `emitWarning()` is the right way, and it might be better to just `console.warn()` instead.  Thoughts?
=> Warn on unknown `options`

.npmignore
Adds an `.npmignore` file to the project so that the final package sent
to NPM is lighter. Tests, examples, and other resources are stripped out
(it's easy to link back to this repository to refer to these if needed).
I've written this is in an "inverted" style so that only by default
everything is blacklisted, and we add back in the files and folders that
we know we'll want.
I verified that this does the right thing by using `npm pack`. Before
the addition of `.npmignore`:
``` sh
$ npm pack && tar -zxf stripe*.tgz && ls -R package/
stripe-6.1.0.tgz
CHANGELOG.md    README.md       examples/       package.json
LICENSE         VERSION         lib/            test/
package//examples:
webhook-signing/
package//examples/webhook-signing:
express.js      package.json
package//lib:
Error.js …
```
=> Add `.npmignore` to create a leaner package

lib/resources/Invoices.js, lib/resources/Subscriptions.js, lib/utils.js, test/resources/Invoices.spec.js, test/utils.spec.js
r? @brandur (But brandur already approved internally, so I'm going to go ahead and self-approve)
This ended up being a bit tricky to figure out where the problem was. It appears the upcoming invoices resource at some point took two URL params, `customerID` and `invoiceOptions`, where `invoiceOptions` was an object with a bunch of parameters. At some point we scrapped `invoiceOptions` and promoted all of its options to be optional top-level fields in the request. 
So now we handle requests in one of two ways:
1. If <=2 parameters, [customerID, {other_stuff}]: customerID and other_stuff appear directly in the URL and are index-encoded properly for array things.
2. If >2 parameters, [customerID, one_field, other_stuff]: customerID and one_field appear directly in the URL. `other_stuff` is in …
=> Upcoming invoices now have proper integer-index-encoded params

lib/resources/Sigma/ScheduledQueryRuns.js, lib/stripe.js, test/resources/Sigma/ScheduledQueryRuns.spec.js
r? @jlomas-stripe @brandur-stripe 
=> Add ScheduledQueryRun resource

lib/resources/Topups.js, test/resources/Topups.spec.js
Add support for the new cancel topup endpoint
r? @remi-stripe || @ob-stripe 
cc @stripe/api-libraries @miguel-stripe @kenneth-stripe @kimberly-stripe
=> Add cancel support for topups

test/flows.spec.js
The test suite is broken because it tries to cancel a subscription with `at_period_end=true`, which is no longer possible with the latest API version. Fixed by changing the request to an update request with `cancel_at_period_end=true`.
=> Fix test suite for latest API version

lib/resources/BitcoinReceivers.js, test/resources/BitcoinReceivers.spec.js, test/resources/Charges.spec.js
Removes `create`, `update`, and `setMetadata` for bitcoin receivers
Tests passing: `407 passing (47s)`
=> Remove editable bitcoin receiver actions

lib/resources/Reporting/ReportRuns.js, lib/resources/Reporting/ReportTypes.js, lib/stripe.js, test/resources/Reporting/ReportRuns.spec.js, test/resources/Reporting/ReportTypes.spec.js
Adding support for the new Reporting resources. Those are in OpenAPI but not yet public but since they are starting to be used and are stable we should merge them.
It's WIP for now while I get some feedback on the implementation and the shape of the resources.
cc @brahn-stripe
=> Add support for the Reporting resources

lib/StripeMethod.basic.js, lib/StripeMethod.js, lib/StripeResource.js, lib/makeRequest.js, lib/resources/FileUploads.js, test/resources/FileUploads.spec.js, testUtils/index.js
r? @brandur-stripe @jlomas-stripe @remi-stripe 
Replaces the `overrideHost` key in `StripeResource` with a `host` key in the `stripeMethod` spec argument. This allows for overriding the host per method instead of per resource.
=> Override host per method instead of per resource

lib/resources/Terminal/ConnectionTokens.js, lib/resources/Terminal/Locations.js, lib/resources/Terminal/Readers.js, lib/stripe.js, test/resources/Terminal/ConnectionTokens.spec.js, test/resources/Terminal/Locations.spec.js, test/resources/Terminal/Readers.spec.js
Bindings for Terminal endpoints
- Connection Tokens
- Locations
- Readers
=> Bindings for Terminal endpoints

lib/resources/Files.js, lib/stripe.js, test/resources/Files.spec.js
- Rename `stripe.fileUploads` to `stripe.files` (but keep `stripe.fileUploads` as an alias for BC)
- Have the retrieve and list requests hit `api.stripe.com` instead of `uploads.stripe.com`
- Have the create request hit `files.stripe.com` instead of `uploads.stripe.com` (this is actually the same host, but `files.stripe.com` is the new canonical name)
=> Rename `FileUploads` to `Files`

.eslintrc.js, README.md, lib/autoPagination.js, test/autoPagination.spec.js
cc @ob-stripe @remi-stripe @jlomas-stripe 
In https://github.com/stripe/stripe-node/issues/511, @tyscorp asked for support for the following (paraphrased slightly): 
```js
stripe.customers.list().autoPagingEach(async function onItem(customer) {
const result = await doSomething(customer);
if (shouldStop(result)) {
return false;
}
});
```
It turns out we already have support for this! The only thing better than inventing a new feature is discovering one. 
I have added a test to verify that this works and prevent regressions, and have added docs to clarify. 
Separately, I have also cleaned up the examples on the home page to better reflect current Node usage (that is, a little more modern).
=> Clarify `autoPagingEach` async usage

lib/resources/Accounts.js, lib/resources/Persons.js, lib/stripe.js, test/resources/Account.spec.js, test/resources/Persons.spec.js
=> Add support for the Person resource

lib/stripe.js, test/stripe.spec.js
This adds support for an optional partner_id attribute in the SetAppInfo hash.
=> Adds support for an optional 'partner_id' parameter in 'setAppInfo'

lib/makeRequest.js, lib/resources/Files.js, lib/utils.js
- Remove a superfluous argument when calling `errorHandler` (the function only accepts a single argument)
- Add a couple of missing semicolons
=> Fix some code quality issues

lib/makeRequest.js, lib/utils.js, test/utils.spec.js
Fixes https://github.com/stripe/stripe-node/issues/521
Also, for good measure, does a shallow copy of request data in general – I don't think there were any other situations that would have mutated this today, and it also doesn't protect against deep mutations, but I don't think it can hurt much (I wouldn't guess that the extra copy operations would have a meaningful perf impact). 
cc @jperasmus
cc @ob-stripe 
cc @enugent-stripe
=> Do not mutate params when encoding arrays as indexed objects

lib/stripe.js, test/flows.spec.js, test/stripe.spec.js
Export errors on root Stripe object, as suggested in https://github.com/stripe/stripe-node/issues/457#issuecomment-441856552.
Also export webhooks because why not.
=> Export errors on root Stripe object

lib/resources/Files.js
The `retrieve` and `list` methods were manually defined on `files` because they used to hit a different host (`files.stripe.com` vs. `api.stripe.com`). Now `files.stripe.com` is only used for upload and download requests and `api.stripe.com` is used for retrieving / listing file objects, so we can use the standard methods.
Fixes #533.
=> Fix iterating on files.list method

lib/MultipartDataGenerator.js, test/Webhook.spec.js
r? @remi-stripe @rattrayalex-stripe 
Using `new Buffer` is deprecated, cf. https://nodejs.org/api/buffer.html#buffer_new_buffer_array. This PR replaces uses of `new Buffer` with `Buffer.alloc(size)` or `Buffer.from(string)` as appropriate.
=> Fix Buffer deprecation warnings

lib/StripeResource.js, lib/stripe.js, test/stripe.spec.js
This PR enables persistent connection by default. From my laptop in Europe, running `test/flows.spec.js` takes 33 seconds with this PR, vs. 1 minute with the master branch.
Tagged as WIP, let me know what you think!
=> Enable persistent connections by default

lib/resources/SubscriptionScheduleRevisions.js, lib/resources/SubscriptionSchedules.js, lib/stripe.js, test/resources/Checkout/Sessions.spec.js, test/resources/PaymentIntents.spec.js, test/resources/SubscriptionSchedule.spec.js, test/resources/SubscriptionScheduleRevision.spec.js
=> Add support for the Subscription Schedule resource

README.md, lib/StripeResource.js, lib/stripe.js, lib/utils.js, package.json, test/StripeResource.spec.js, test/stripe.spec.js
Fixes https://github.com/stripe/stripe-node/issues/558
Adds network retry functionality. The default retry amount is 0 but can be changed via `stripe.setMaxNetworkRetries(n)`. I modeled this after a similar change in `stripe-php`: https://github.com/stripe/stripe-php/pull/428/files
In the case of a `POST` request, an idempotency key is generated if not already provided.
This also adds the `uuid` and `nock` libraries. The former is for generating idempotency keys, there already is a similar function used in testing however according to our docs \[0\] `uuid/v4` should ideally be used for real requests. I use `nock` to mock API responses and failures.
\[0\]: https://stripe.com/docs/api/idempotent_requests
=> Network retries

README.md, lib/StripeResource.js
We removed network retries for rate limiting errors in https://github.com/stripe/stripe-node/pull/559 for now, but accidentally left references to it in the README.md and comments. This fixes that.
=> Remove rate limiting language

README.md
cc @paulasjes-stripe 
cc @brandur-stripe 
Follows https://github.com/stripe/stripe-node/pull/566 which follows https://github.com/stripe/stripe-node/pull/559
=> Clarify that automatic network retries occur for most api errors

lib/resources/Invoices.js, lib/resources/Subscriptions.js, lib/utils.js, package.json, test/StripeResource.spec.js, test/resources/Invoices.spec.js, test/resources/Subscriptions.spec.js, test/utils.spec.js
r? @brandur-stripe @rattrayalex-stripe 
Always encode arrays as integer-indexed hashes. This is the default behavior of `qs.stringify()`. Stripe's API can now accept integer-indexed hashes for all array parameters (including `expand`) so there is no longer a need to special-case arrays of hashes parameters like `subscription_items`.
I've also updated the encoding method to change square brackets back to their literals to make the strings easier to read. This is consistent with most of our other libraries.
Fixes #561.
=> Always encode arrays as integer-indexed hashes

lib/utils.js, test/utils.spec.js
Encode `Date`s as Unix timestamps, using [`qs`](https://github.com/ljharb/qs)' `serializeDate` option.
Fixes #569.
=> Encode Dates as Unix timestamps

lib/StripeResource.js, lib/stripe.js, test/stripe.spec.js
When I enabled persistent connections in #560, I broke support for HTTPS proxies: instances of `HttpsProxyAgent` are not instances of `https.Agent`, so they are assigned to `http_agent` instead of `https_agent`.
Rather than try to store all possible agent types in the correct variable, this PR reverts to the previous behavior of storing the agent in `agent` regardless of its type. If `agent` is null,`StripeResource` will use a default agent of the correct type depending on whether the request uses HTTP or HTTPS.
Fixes #579.
=> Fix support for HTTPS proxies

lib/resources/Checkout/Sessions.js, test/resources/Checkout/Sessions.spec.js
This adds support for retrieving a Checkout Session via the API and also changes the shape of the resource to have more details.
=> Add support for retrieving a Checkout Session

lib/resources/Customers.js, lib/resources/TaxIds.js, lib/stripe.js, test/resources/Customers.spec.js, test/resources/TaxIds.spec.js
=> Add support for the TaxId resource and APIs

lib/stripe.js
Currently the User-Agent builder attempts to spawn a sub shell (default of `/bin/sh`) to execute `uname -a`. 
In high security environments where the application runtime is not permitted access to `/bin/sh` (or any external shell), Node will throw a `spawn EACCES` error rather than populating the `error` object. This is a common case when restricting an application with SELinux or AppArmor. 
These errors are not handled gracefully by the library and cause a hard crash. In general, given the myriad of execution environments as well, this call should be fully captured within an error handler. 
This PR adds proper error handling to the child_process execution to prevent shell related errors from breaking the library. 
The main logic for building the UA string is broken into a private helper …
=> Add error handling to User-Agent builder

lib/stripe.js, lib/utils.js, test/stripe.spec.js, test/utils.spec.js
This is a follow-up to https://github.com/stripe/stripe-node/pull/597 that incorporates [feedback](https://github.com/stripe/stripe-node/pull/597/files#r277846768) from @brandur-stripe 
It also fixes a (small) longstanding bug coming from brandur's hunch; in the `err` case, [this line](https://github.com/stripe/stripe-node/blob/140fd420fbc5407973afff71a578de69e1e1bd3d/lib/stripe.js#L306) would produce `"null"` instead of `"UNKNOWN"`, as intended.
@brennentsmith 's PR introduced no regressions and was minimally-invasive, just taking this opportunity to add some tests for confidence and rework the API a bit (I needed to move things into `utils` anyway for mockability, and figured it was silly _not_ to expose the safer api if I'm already moving things into a utils file – that's what they're …
=> Rework error handling around exec

lib/MultipartDataGenerator.js, lib/utils.js, test/resources/FileUploads.spec.js, test/resources/Files.spec.js, test/utils.spec.js
Allows for nested parameters in multipart requests (i.e. file creation requests).
=> Flatten parameters in multipart requests

examples/webhook-signing/express.js, examples/webhook-signing/package.json
Old example was from 2017 and was confusing people. Particularly since `body-parser` is now included automatically with Express and no longer needs to be installed by NPM/Yarn. 
New example is now more in line to what the official docs say: https://stripe.com/docs/webhooks/signatures
Alternatively, we could just remove the examples folder entirely and direct people to the docs instead.
r? @rattrayalex-stripe
=> Updated webhook signing example

lib/Error.js, lib/StripeResource.js, test/StripeResource.spec.js
Before this change, failures from the OAuth API would result in `Invalid JSON received from the Stripe API` errors.
The cause was not a parse error, but an error thrown at https://github.com/stripe/stripe-node/compare/master...mdlavin:handle-oauth-errors?expand=1#diff-404ddfdf655bbca4b088b8c7242d0a3aL155 when the `headers` value was assigned to a string value.
The response body coming back from the oauth/token endpoint is:
```
{
"error":"invalid_grant",
"error_description":"This authorization code has already been used. All tokens issued with this code have been revoked."
}
```
As described in https://stripe.com/docs/connect/oauth-reference#post-token-errors
I also added a nicely typed Error for invalid_token responses, and the other OAuth failures will be reported as Generic errors …
=> Handle errors from the oauth/token endpoint

lib/resources/BitcoinReceivers.js, lib/resources/Charges.js, lib/resources/CreditNotes.js, lib/resources/Customers.js, lib/resources/Invoices.js, lib/resources/Orders.js, lib/resources/PaymentIntents.js, lib/resources/PaymentMethods.js, lib/resources/Payouts.js, lib/resources/Recipients.js, lib/resources/Subscriptions.js, lib/resources/Topups.js, lib/resources/Transfers.js, lib/resources/UsageRecords.js
Use `id` for single resource method positional arguments, e.g.:
```javascript
cancel: stripeMethod({
method: 'POST',
path: '{id}/cancel',
urlParams: ['id'],
})
```
Instead of:
```javascript
cancel: stripeMethod({
method: 'POST',
path: '{paymentIntentId}/cancel',
urlParams: ['paymentIntentId'],
})
```
1. Modify argument names for methods with multiple positional arguments, e.g.
```javascript
updateRefund: stripeMethod({
method: 'POST',
path: '/{chargeId}/refunds/{refundId}',
urlParams: ['chargeId', 'refundId'],
}),
```
2. Modify argument names in resource paths, e.g.
```javascript
module.exports = StripeResource.extend({
path: 'application_fees/{feeId}/refunds',
includeBasic: ['create', 'list', 'retrieve', 'update'],
});
```
=> Use `id` for single positional arguments

lib/resources/BalanceTransactions.js, lib/stripe.js, test/resources/BalanceTransactions.spec.js
r? @rattrayalex-stripe @remi-stripe 
Adds a `stripe.balanceTransactions` resource with `list()` and `retrieve()` methods.
Right now balance transactions can be accessed via `stripe.balance.listTransactions()` / `retrieveTransaction()`, but balance transactions are not really a nested resource, they just have a somewhat weird URL pattern.
=> Add BalanceTransactions resource

.eslintignore, README.md, lib/stripe.js, test/Webhook.spec.js, testUtils/index.js
Fixes https://github.com/stripe/stripe-node/issues/601
Exposes `generateWebhookHeaderString` so users can mock Stripe webhook events. This feature already existed within the repo, this just lets others play with it.
I moved some constants around and changed `generateHeaderString` to also accept an instance of `stripe`, in case you already have a spyable instance you want to reuse.
r? @rattrayalex-stripe @ob-stripe
=> Exposing generateHeaderString as generateWebhookHeaderString

README.md, lib/Webhooks.js, lib/stripe.js, test/Webhook.spec.js, testUtils/index.js
Attempt 2!
Moved the header generator to a more reasonable place. This version is a little more strict with what you pass in, this is mainly because we don't want test constants in non-test code.
Also no longer requiring things that aren't whitelisted in `.npmignore`.
r? @rattrayalex-stripe @ob-stripe
=> Move generateTestHeaderString to stripe.webhooks

.travis.yml, package.json, yarn.lock
Bump all dependencies to their latest versions.
=> Drop support for Node 9 and bump dependencies to latest versions

lib/resources/Invoices.js, test/StripeResource.spec.js, test/resources/Invoices.spec.js
r? @rattrayalex-stripe @remi-stripe 
cc @stripe/api-libraries @irace-stripe 
- Removes support for legacy customer and subscription parameters in `invoices.retrieveUpcoming()`. All parameters must now be provided in a hash.
- While I was at it, I also noticed that `retrieveLines()` should really be called `listLineItems()` because it returns a list object containing a list of `line_item`s.
- I also added `listUpcomingLineItems()` because I think that's much cleaner than telling users to use `listLines()` with `"upcoming"` as the ID.
=> Remove legacy parameter support in invoices.retrieveUpcoming()

lib/resources/Invoices.js, test/resources/Invoices.spec.js
We added these two methods in the v7 branch. I'd like to add them to the last 6.x version to make the upgrade path a bit easier, and so that people who need or want to stay on the 6.x branch for a bit can still use these methods (which will be the officially documented ones in the API reference).
=> Add listLineItems and listUpcomingLineItems methods

lib/resources.js, lib/resources/Radar/EarlyFraudWarnings.js, test/resources/Radar/EarlyFraudWarnings.spec.js
Add support for `radar.early_fraud_warning` resource
=> Add support for radar.early_fraud_warning resource

README.md, lib/stripe.js, test/telemetry.spec.js
r? @brandur-stripe @rattrayalex-stripe
Cf. https://github.com/stripe/stripe-ruby/pull/800.
=> Enable request latency telemetry by default

lib/resources.js, lib/resources/SetupIntents.js, test/resources/SetupIntents.spec.js
I used the autogen tool to generate the code. I just manually removed the changes to Customers.js as those were incorrect 
=> Add support for the `SetupIntent` resource and APIs

README.md
While looking at retry code samples across client libraries recently, we
happened to notice that all the other ones use two retries as an example
while stripe-node uses one.
Definitely not adverse to changing this number everywhere at some point
if we think it's right move, but for now just doing the incremental
improvement of making stripe-node consistent with the other libraries.
r? @brandur-stripe (Tiny change. Going to self-approve this one.)
=> Update README retry code sample to use two retries

lib/utils.js, test/utils.spec.js
r? @ob-stripe 
cc @stripe/api-libraries @jlomas-stripe @paulasjes-stripe @remi-stripe 
`isAuthKey` relies on a regex which assumes a fixed length of a secret key token. This assumption recently broke. 
Looking at the code, passing a string which does not fit the regex currently noops completely, so I chose to simply check whether it is a non-empty string and if so, assume it is an auth key. 
Note that you could maybe interpret this to be a breaking change, because you could have previously written this: 
```js
stripe.customers.retrieve('cus_123', 'garbage');
```
which would have been equivalent to `stripe.customers.retrieve('cus_123')` and worked fine, but with this change would fail with a bad secret key. 
I think that's fine, but not sure and want to check with others. 
Relatedly, I …
=> Interpret any string in options as an API Key instead of using a regex

lib/MultipartDataGenerator.js, lib/Webhooks.js, lib/resources/Files.js, lib/utils.js, package.json, test/Webhook.spec.js, test/utils.spec.js, yarn.lock
`safe-buffer` does nothing when native `Buffer.from` API is available and it's available since Nodes.JS 5.10 (https://nodejs.org/api/buffer.html#buffer_class_method_buffer_from_array), so, there is no sense to bring it as production dependency (one of four) when your declared minimum supported Node.JS version is 6.x.
=> Remove `safe-buffer` dependency

lib/StripeResource.js, lib/resources/Files.js, lib/stripe.js, test/flows.spec.js
Fixes a misspelling in EventEmitter property declaration, exposes `once` method and uses `once` where it's more appropriate than `on`
=> Expose and use `once`

README.md, lib/StripeResource.js, lib/utils.js, test/StripeResource.spec.js, test/utils.spec.js
cc @paulasjes-stripe @jlomas-stripe @ob-stripe 
r? @richardm-stripe (account doesn't exist yet, need to work on that)
Trying to carefully review https://github.com/stripe/stripe-node/pull/663 made my head spin as I tried to track through how we set headers. 
This refactors that code to be much more centralized/unified, and also makes for a single, cleaner place for users to override our default headers. 
However, this introduces a few possible subtle changes of behavior which I'm worried about: 
1) If, for some reason, any of the fields in my `defaultHeaders` variable get set to empty-string, they will now send the header key with no value (I think this would only apply to `apiVersion` and I don't think that's likely to happen and I don't _think_ there would be a consequence of it). 
2) …
=> Refactor headers

lib/StripeResource.js, lib/utils.js, package.json, test/StripeResource.spec.js
cc @stripe/api-libraries @paulasjes-stripe @ob-stripe @brandur-stripe 
I checked and this should be well within our idempotency key length limits.
=> Remove uuid dep, include a prefix in generated idempotency keys

lib/Error.js, test/Error.spec.js
This is a follow-on to https://github.com/stripe/stripe-node/pull/661
It makes several small changes but the most consequential are:
1) Adding `get type()` support on `StripeError`, so subclasses have the property `new StripeFooClass({}).type === 'StripeFooClass'`, which is an important property to uphold. We missed this in #661 because our `StripeError` tests had actually been testing `GenericError` on accident, oops!
2) Remove support for magical `.name`, which turned out not to be important for backcompat (previously `.name` was just `'Error'`) – was a mistake for me to ask for that.
3) Have `StripeError` inherit directly from `Error`, and have the default export of `Error.js` be an "old-school class" to maximize backcompat without any complexity leaking into our proper base class, and …
=> Separate super-deprecated errors from base errors, fix type override, and remove name override

README.md, lib/StripeResource.js, test/flows.spec.js
I am working on setting up distributed tracing for work and I am wanting to create spans on our Stripe calls. This change makes it easier to get accurate start and end times for the spans. Plus I think this addition should be beneficial for other people as well.
=> Add request start and end time to request and response events

lib/multipart.js, lib/resources/Files.js
cc @ob-stripe @stripe/api-libraries 
This was in a codegen'd file, which lead to big/ugly diffs; we should ~never have substantial application logic in a codegen'd file.
While I was looking at the code, I refactored to make it a bit more simple/modern/unified.
=> Refactor requestDataProcessor for File out into its own file

lib/StripeMethod.js, lib/makeRequest.js, package.json, test/StripeResource.spec.js, test/mocha.opts, test/resources/BitcoinReceivers.spec.js, test/resources/CreditNotes.spec.js, test/resources/Events.spec.js, test/resources/Invoices.spec.js, test/resources/OrderReturns.spec.js, test/resources/Orders.spec.js, test/resources/PaymentMethods.spec.js, test/resources/Products.spec.js, test/resources/Radar/ValueListItems.spec.js, test/resources/SKUs.spec.js, test/resources/SubscriptionItems.spec.js, test/resources/Subscriptions.spec.js
r? @ob-stripe 
cc? @rattrayalex-stripe @remi-stripe 
Addresses #690 -- whenever an ApiResource method is called that corresponds to a GET or DELETE, those properties are attached to the end of the path.
I think this should be safe, assuming:
1. "Path" never already contains a query string.
2. No users are sending bodies large enough to risk hitting some sort of URL length limit.
I also changed `mocha.opts` not to bail by default. Rationale: I couldn't find a way to override this from the command-line (but it's easy to add `-b` if that's what you want), and I prefer not-bailing in cases where I need to make simple changes in many tests.
=> GET and DELETE requests data: body->queryParams

lib/StripeResource.js, test/StripeResource.spec.js
r? @ob-stripe 
cc @stripe/api-libraries @paulasjes-stripe @jlomas-stripe
This adds support for the `Stripe-Should-Retry` and `Retry-After` headers. 
This allows the API to specify specific cases when an automatic retry is recommended (such as `lock_timeout` errors) or not recommended (such as when our idempotency framework would replay the request anyway). 
It also allows the API to encourage slower retries.
=> Retry based on `Stripe-Should-Retry` and `Retry-After` headers

lib/Error.js, test/Error.spec.js
Per request of @remi-stripe (https://jira.corp.stripe.com/secure/RapidBoard.jspa?rapidView=1346&projectKey=DX&view=planning&selectedIssue=DX-4753&quickFilter=3988)
It is sometimes important to access properties such as `error.raw.payment_intent`, `error.raw.payment_method`, etc. But "raw" means "here be dragons, don't rely on anything here". This PR copies these properties from `raw` to the top level error object, to indicate that they are properly part of our interface and remove the need for users to access "raw".
=> Add request-specific fields from raw error to top level error

lib/stripe.js, test/stripe.spec.js
Adds the following properties to the config object:
```
'maxNetworkRetries',
'httpAgent',
'timeout',
'host',
'port',
'telemetry'
```
Means you can now set these properties like so:
```js
const stripe = new Stripe('sk_test_123', {
maxNetworkRetries: 2,
httpAgent: new ProxyAgent(process.env.http_proxy),
timeout: 1000,
host: 'api.stripe.zonks',
port: 123,
telemetry: false,
});
```
Properties that I expect to only be set once (e.g. httpAgent and host) I added a deprecated warning to their old setter functions. Properties which you could possibly want to change after initialization (e.g. telemetry and timeout) I left the setters as is.
For network retries, does it make sense to remove the setter and favor set on initialization/override per request or should we leave the setter in? I changed it …
=> Add properties to new config object

README.md
This is subjective.
I read it several times as the node API docs (e.g https://nodejs.org/api/),  and somehow skipped it.
Up to you whether this is any better.
=> README: imply context of stripe-node

README.md
Updated README to contain info on how to use the config object and how to use `setMaxNetworkRetries` and `timeout` on a per-request basis.
Once the long running branch lands, I'll need to update the [wiki](https://github.com/stripe/stripe-node/wiki/Passing-Options) to reflect these changes.
r? @rattrayalex-stripe @jlomas-stripe
=> Add new config object to README

test/resources/Mandates.spec.js
This test has been failing since https://github.com/stripe/stripe-node/commit/265827e3b2a64b781f8cccd967f19eed89751e4a -- somehow it didn't get updated like the others.
=> Update test to expect new config

lib/StripeMethod.js
=> Remove duplicate export

test/flows.spec.js
r? @ob-stripe 
cc @justinmichael-stripe @remi-stripe  @stripe/api-libraries 
The test started failing - the status was 402 instead of 400 - with this error message: 
```
You cannot create a charge on a connected account without the card_payments capability enabled.
```
I think this change preserves the intent.
We should really move to stripe-mock.
=> Fix flows test

types/2019-12-03/SubscriptionSchedules.d.ts
`SubscriptionSchedules.Phase.Plan.plan` was incorrectly using type `SubscriptionSchedules.Phase.Plan` so I changed it to use type `Stripe.Plan` as described [here](https://stripe.com/docs/api/subscription_schedules/object#subscription_schedule_object-phases-plans-plan)
=> Update SubscriptionSchedules.Phase.Plan.plan to use correct type

lib/Error.js, lib/stripe.js, lib/utils.js, test/Error.spec.js, test/StripeResource.spec.js, test/flows.spec.js, test/resources/Account.spec.js, test/resources/Customers.spec.js, test/resources/EphemeralKeys.spec.js, test/utils.spec.js, types/lib.d.ts, types/test/typescriptTest.ts
cc @ob-stripe @jlomas-stripe @paulasjes-stripe 
Much of the tricky stuff here is wrestling with questions of what should be private, what should be private-but-you-can-poke-it-anyway, etc. It might be healthier for my sanity to kick these cans down the road a bit more, but probably healthier for the library to deal with them sooner rather than later, especially if we want to upgrade our internals to TS etc in the medium term.
---
You can no longer do this:
const MyStripeError = StripeError.extend({});
Instead, you can do this:
class MyStripeError extends StripeError {}
You can no longer do this (which should not have had a legitimate use-case):
const StripeGenericError = require('stripe/lib/Error');
Instead, use the named export `StripeError`:
const {StripeError} = …
=> Deprecate many library api's, unify others

lib/StripeResource.js, lib/Webhooks.js, test/Webhook.spec.js, types/Webhooks.d.ts
When trying out the new library, Thor found that express's TS types indicate that a header is typed as `string | []string`. 
This resulted in the following type error:
His workaround was to do a cast:
```tsx
const signature: string = req.headers["stripe-signature"] as string;
event = stripe.webhooks.constructEvent(
req.body,
signature,
process.env.STRIPE_WEBHOOK_SECRET
);
```
but it'd be nice to not have to do that, and have this Just Work:
```tsx
event = stripe.webhooks.constructEvent(
req.body,
req.headers["stripe-signature"],
process.env.STRIPE_WEBHOOK_SECRET
);
```
This turns out to be because express's `Request` class [is a wrapper](https://github.com/expressjs/express/blob/master/lib/request.js#L31) around `http.IncomingMessage`, and …
=> Accept an array of strings or buffers as the header argument for webhooks.constructEvent

types/2019-12-03/Accounts.d.ts, types/2019-12-03/Balance.d.ts, types/2019-12-03/Charges.d.ts, types/2019-12-03/Checkout/Sessions.d.ts, types/2019-12-03/Events.d.ts, types/2019-12-03/Issuing/Cardholders.d.ts, types/2019-12-03/Payouts.d.ts, types/2019-12-03/Persons.d.ts, types/2019-12-03/SubscriptionItems.d.ts, types/2019-12-03/Subscriptions.d.ts, types/2019-12-03/Tokens.d.ts
Makes many markdown links be full URL's instead of relative paths or hashes, so that cmd+click in IDE's works.
=> Improve markdown links in TS comments

.npmignore, lib/stripe.js
r? @jlomas-stripe 
Fixes https://github.com/stripe/stripe-node/issues/756
Tested in a repl:
```
> require('./lib/stripe')('hi'); 1
1
> require('./lib/stripe')('hi').customers.list(); 1
1
> (node:46965) UnhandledPromiseRejectionWarning: Error: Invalid API Key provided: hi
```
Note that it did not log warnings.
=> Add types dir to npmignore whitelist and stop warning when instantiating stripe with no args

lib/resources/CreditNotes.js, test/resources/CreditNotes.spec.js, types/2019-12-03/Accounts.d.ts, types/2019-12-03/CreditNoteLineItems.d.ts, types/2019-12-03/CreditNotes.d.ts, types/2019-12-03/index.d.ts
Codegen for openapi d663cdb
r? @ob-stripe 
=> Add support for listing line items on a `CreditNote`

types/2019-12-03/InvoiceLineItems.d.ts, types/2019-12-03/Invoices.d.ts, types/2019-12-03/SubscriptionItems.d.ts, types/2019-12-03/Subscriptions.d.ts
=> Add support for `pending_update` on `Subscription`

types/2019-12-03/Checkout/Sessions.d.ts, types/2019-12-03/Issuing/Cardholders.d.ts, types/2019-12-03/Issuing/Cards.d.ts, types/2019-12-03/Products.d.ts, types/2019-12-03/SetupIntents.d.ts, types/2019-12-03/Terminal/ConnectionTokens.d.ts, types/2019-12-03/Terminal/Locations.d.ts, types/2019-12-03/Terminal/Readers.d.ts
Codegen for openapi fd2f212
r? @ob-stripe 
=> Add `metadata` on Checkout `Session` and remove deprecated features

lib/resources/Accounts.js, lib/resources/Customers.js, lib/resources/Invoices.js, lib/resources/Subscriptions.js, types/2019-12-03/Customers.d.ts, types/2019-12-03/Invoices.d.ts, types/2019-12-03/TaxIds.d.ts
=> Add support for new `type` on `CustomerTaxId`

lib/utils.js, test/utils.spec.js
As reported in #773, it seems that certain sandboxed environments like
CloudFlare Workers don't provide a `subprocess` module, and that causes
Node to throw when we try to require it.
Because the only thing we need `subprocess` for is getting `uname`, here
we extend the already-existing infrastructure built to gracefully handle
errors to also be able to handle this new error case.
Fixes #773.
r? @rattrayalex-stripe (Or recommend another reviewer if you like.)
=> Gracefully handle a missing `subprocess` module

types/2019-12-03/InvoiceLineItems.d.ts, types/2019-12-03/Invoices.d.ts, types/2019-12-03/Issuing/Cards.d.ts, types/2019-12-03/Subscriptions.d.ts
Codegen for openapi 32bf030
r? @ob-stripe 
=> Add support for `shipping[speed]` on Issuing `Card`

lib/multipart.js, testUtils/index.js
Previously we were getting our keys from a flattened object, but then using the flattened key to access the original object, so 💥.
Now with 100% less 💥.
=> Fix file uploads with nested params

types/2019-12-03/Tokens.d.ts
tokens.create allows for [cloning payment methods][1] from one account to another through stripe connect. When cloning a source, you do not provide the full payment method information but just the string id for the source in the appropriate key (card for credit cards and bank_account for bank accounts).
This was done correctly for credit cards but was not done for bank accounts. We are getting around this currently by using `as any` to ignore the typescript errors and allow passing a string as the bank_account.
[1]: https://stripe.com/docs/connect/cloning-saved-payment-methods
=> Allow bank account id to be provided to tokens.create

README.md, examples/webhook-signing/typescript-node-express/express-ts.ts, types/lib.d.ts, types/test/typescriptTest.ts
r? @richardm-stripe || @ob-stripe 
We had added this so that our user-agent would specify whether a request came from TS vs vanilla JS. We use language/runtime information for product planning purposes, but in this case don't anticipate the information being useful enough to justify the annoyance/confusion of an extra param for the user.
=> Make typescript param optional

types/2019-12-03/Accounts.d.ts, types/2019-12-03/Checkout/Sessions.d.ts, types/2019-12-03/Plans.d.ts, types/2019-12-03/Products.d.ts
Codegen for openapi 92625ac
r? @ob-stripe 
=> Add support for `company.structure` on `Account` and other docs changes

types/2019-12-03/SourceTransactions.d.ts, types/2019-12-03/SubscriptionSchedules.d.ts, types/2019-12-03/Subscriptions.d.ts
Codegen for openapi f9f9b8b
r? @ob-stripe 
=> Rename `sort_code` to `sender_sort_code` on `SourceTransaction` for BACS debit

types/2019-12-03/Cards.d.ts, types/2019-12-03/Charges.d.ts, types/2019-12-03/Checkout/Sessions.d.ts, types/2019-12-03/CreditNoteLineItems.d.ts, types/2019-12-03/CreditNotes.d.ts, types/2019-12-03/CustomerBalanceTransactions.d.ts, types/2019-12-03/Customers.d.ts, types/2019-12-03/Invoices.d.ts, types/2019-12-03/Issuing/Authorizations.d.ts, types/2019-12-03/Issuing/Disputes.d.ts, types/2019-12-03/Mandates.d.ts, types/2019-12-03/PaymentMethods.d.ts, types/2019-12-03/TaxIds.d.ts, types/2019-12-03/Tokens.d.ts
Multiple API changes
* Add support for new `type` values for `TaxId`.
* Add support for `payment_intent_data[statement_descriptor_suffix]` on Checkout `Session`.
Codegen for openapi 7562c6b
r? @ob-stripe 
=> Multiple API changes

types/2019-12-03/Balance.d.ts, types/2019-12-03/Checkout/Sessions.d.ts, types/2019-12-03/Issuing/Authorizations.d.ts, types/2019-12-03/PaymentIntents.d.ts, types/2019-12-03/PaymentMethods.d.ts, types/2019-12-03/Payouts.d.ts, types/2019-12-03/Plans.d.ts, types/2019-12-03/SetupIntents.d.ts, types/2019-12-03/Transfers.d.ts
Multiple API changes reflected in Typescript definitions
* Add `fpx` as a valid `source_type` on `Balance`, `Payout` and `Transfer`
* Add `fpx` support on Checkout `Session`
* Fields inside `verification_data` on Issuing `Authorization` are now enums
* Support updating `payment_method_options` on `PaymentIntent` and `SetupIntent`
Codegen for openapi 9f798bd
r? @ob-stripe 
=> Multiple API changes reflect in Typescript definitions

types/2019-12-03/Checkout/Sessions.d.ts, types/2019-12-03/PaymentIntents.d.ts
Codegen for openapi 277f09c
r? @ob-stripe 
=> Add support for `payment_intent_data[transfer_data][amount]` on Checkout `Session`

types/2019-12-03/CreditNoteLineItems.d.ts, types/2019-12-03/CreditNotes.d.ts, types/2019-12-03/Customers.d.ts, types/2019-12-03/InvoiceItems.d.ts, types/2019-12-03/InvoiceLineItems.d.ts, types/2019-12-03/Invoices.d.ts, types/2019-12-03/Issuing/Authorizations.d.ts, types/2019-12-03/Issuing/Cards.d.ts, types/2019-12-03/Issuing/Transactions.d.ts, types/2019-12-03/Orders.d.ts, types/2019-12-03/PaymentIntents.d.ts, types/2019-12-03/PaymentMethods.d.ts, types/2019-12-03/Persons.d.ts, types/2019-12-03/Plans.d.ts, types/2019-12-03/Products.d.ts, types/2019-12-03/SetupIntents.d.ts, types/2019-12-03/Sources.d.ts, types/2019-12-03/SubscriptionItems.d.ts, types/2019-12-03/SubscriptionSchedules.d.ts, types/2019-12-03/Subscriptions.d.ts, types/2019-12-03/Tokens.d.ts
r? @ob-stripe 
cc @jlomas-stripe @stripe/api-libraries 
1. More consistently encode "emptyStringable" types (described in the openapi spec as `anyOf(X, enum([''])`) as `X | null` instead of `X | ''`.
2. Fixes issue #766
3. A little bit of churn re: ordering of things because of codegen changes.
=> TS Fixes: arrays of subobjects, emptyStringable fields

README.md, lib/stripe.js, test/stripe.spec.js, types/lib.d.ts
Closes #806 
Set `timeout` default to a constant 80 seconds instead of using the default value of the version of Node.js the user is running.
Updated tests, docs, comment in types def file.
**Note**: Not sure how you define breaking changes here, but this would be a departure from the previous default behavior of 120 seconds. This issue is currently out in the wild though (for anyone _\*brave\*_ enough to be using v13 in production) so I would suggest a release as soon as feasible. 
Switching this back to a constant 120 seconds and a minor version bump would prevent anyone from encountering the issue in the current major.
=> Change timeout default to constant 80000 instead Node default

lib/resources/Checkout/Sessions.js, types/2019-12-03/Checkout/Sessions.d.ts
Codegen for openapi fd4c483
r? @ob-stripe
=> Add support for listing Checkout `Session` and passing tax rate information

types/lib.d.ts
This matches the implemented type
fixes #823
=> Update type for StripeError to extend Error

lib/makeRequest.js, test/StripeResource.spec.js
I ran out of time trying to write an automated test for this. I'm not familiar with this nock tooling and was able to get past the root error and my basic test passing locally. Also, didn't see a compact helper so just used this filter.
This is to address #825 
```
(async () => {
const id = 'acct_1GBs7XDllkSPMYqA';
const account = await stripe.accounts.retrieve(id)
console.log(account)
const account2 = await stripe.accounts.retrieve(id, undefined)
console.log(account2)
})();
```
=> Improve args check to support optional params for makeRequest

types/2020-03-02/Issuing/Authorizations.d.ts, types/2020-03-02/Issuing/Disputes.d.ts, types/2020-03-02/PaymentIntents.d.ts, types/2020-03-02/Plans.d.ts, types/2020-03-02/Products.d.ts, types/2020-03-02/SetupIntents.d.ts
Codegen for openapi f8c0941
Docs: https://stripe.com/docs/api/issuing/authorizations/object#issuing_authorization_object-verification_data-three_d_secure
r? @ob-stripe 
=> Add support for `ThreeDSecure` on Issuing `Authorization`

types/2020-03-02/Charges.d.ts, types/2020-03-02/Checkout/Sessions.d.ts, types/2020-03-02/IssuerFraudRecords.d.ts, types/2020-03-02/Issuing/Authorizations.d.ts, types/2020-03-02/Issuing/Cardholders.d.ts, types/2020-03-02/Issuing/Cards.d.ts, types/2020-03-02/PaymentIntents.d.ts, types/2020-03-02/SetupIntents.d.ts
Multiple API changes for Issuing:
* Add `amount`, `currency`, `merchant_amount` and `merchant_currency` on `Authorization`
* Add `amount`, `currency`, `merchant_amount` and `merchant_currency` inside `request_history` on `Authorization`
* Add `pending_request` on `Authorization`
* Add `amount` when approving an `Authorization`
* Add `replaced_by` on `Card`.
Codegen for openapi 442098c
r? @ob-stripe 
=> Multiple API changes for Issuing and other docstrings

types/2020-03-02/Accounts.d.ts, types/2020-03-02/Charges.d.ts, types/2020-03-02/Mandates.d.ts, types/2020-03-02/PaymentMethods.d.ts
=> Add new capabilities for AU Becs Debit and tax reporting

types/2020-03-02/Cards.d.ts, types/2020-03-02/Charges.d.ts, types/2020-03-02/Issuing/Cardholders.d.ts, types/2020-03-02/Issuing/Cards.d.ts, types/2020-03-02/Issuing/Disputes.d.ts, types/2020-03-02/PaymentMethods.d.ts, types/2020-03-02/Subscriptions.d.ts
Codegen for openapi cadc76e
r? @ob-stripe 
=> Add support for `pause_collection` on `Subscription`

types/2020-03-02/Charges.d.ts, types/2020-03-02/Checkout/Sessions.d.ts, types/2020-03-02/Issuing/Authorizations.d.ts, types/2020-03-02/Issuing/Cardholders.d.ts, types/2020-03-02/Issuing/Cards.d.ts, types/2020-03-02/Issuing/Transactions.d.ts, types/2020-03-02/PaymentIntents.d.ts, types/2020-03-02/Sources.d.ts, types/2020-03-02/SubscriptionItems.d.ts
Codegen for openapi afb5b18
r? @richardm-stripe @rattrayalex-stripe 
=> Add support for `calculatedStatementDescriptor` on `Charge`

types/lib.d.ts
`autoPagingEach` returns a `Promise`
=> Fix return type for autoPagingEach

types/2020-03-02/Issuing/Authorizations.d.ts, types/2020-03-02/Issuing/Cards.d.ts, types/2020-03-02/Issuing/Transactions.d.ts, types/2020-03-02/Payouts.d.ts, types/2020-03-02/SubscriptionSchedules.d.ts, types/2020-03-02/WebhookEndpoints.d.ts
Codegen for openapi 34ddc7f
r? @ob-stripe 
=> Add support for `description` on `WebhookEndpoint`

types/2020-03-02/Accounts.d.ts, types/2020-03-02/PaymentIntents.d.ts, types/2020-03-02/PaymentMethods.d.ts, types/2020-03-02/SetupIntents.d.ts
=> Add support for `settings[branding][secondary_color]` on `Account`

types/2020-03-02/BillingPortal/Sessions.d.ts, types/2020-03-02/Checkout/Sessions.d.ts
=> Add support for `Coupon` when for subscriptions on Checkout

types/2020-03-02/Accounts.d.ts, types/2020-03-02/Checkout/Sessions.d.ts, types/2020-03-02/Invoices.d.ts, types/2020-03-02/Products.d.ts, types/2020-03-02/SubscriptionItems.d.ts
=> Add support for `jcb_payments` as a `Capability`

types/2020-03-02/Checkout/Sessions.d.ts, types/2020-03-02/InvoiceLineItems.d.ts
Codegen for openapi 3b0ec34
r? @ob-stripe 
=> Make `display_items` on Checkout `Session` optional

lib/resources.js, lib/resources/Prices.js, test/resources/Prices.spec.js, types/2020-03-02/InvoiceItems.d.ts, types/2020-03-02/InvoiceLineItems.d.ts, types/2020-03-02/Invoices.d.ts, types/2020-03-02/Prices.d.ts, types/2020-03-02/SubscriptionItems.d.ts, types/2020-03-02/SubscriptionSchedules.d.ts, types/2020-03-02/Subscriptions.d.ts, types/2020-03-02/index.d.ts
Codegen for openapi f75fd88
r? @ob-stripe 
cc @stripe/api-libraries @areagle-stripe
=> Add support for the `Price` resource and APIs

lib/resources/Checkout/Sessions.js, test/resources/Checkout/Sessions.spec.js, types/2020-03-02/Accounts.d.ts, types/2020-03-02/Checkout/Sessions.d.ts, types/2020-03-02/Coupons.d.ts, types/2020-03-02/Invoices.d.ts, types/2020-03-02/LineItems.d.ts, types/2020-03-02/Plans.d.ts, types/2020-03-02/Prices.d.ts, types/2020-03-02/Subscriptions.d.ts, types/2020-03-02/index.d.ts
=> Add support for the `LineItem` resource and APIs

types/2020-03-02/Checkout/Sessions.d.ts, types/2020-03-02/Issuing/Transactions.d.ts
=> Add support for `purchase_details` on Issuing `Transaction`

README.md
Mention `ts-ignore` as appropriate for betas in the section of the README.md where we suggest using `@ts-ignore` for old api versions.
see #892
=> README: Suggest @ts-ignore for betas

types/2020-03-02/Accounts.d.ts, types/2020-03-02/Charges.d.ts, types/2020-03-02/Checkout/Sessions.d.ts, types/2020-03-02/Mandates.d.ts, types/2020-03-02/PaymentMethods.d.ts, types/2020-03-02/Persons.d.ts, types/2020-03-02/Plans.d.ts, types/2020-03-02/Tokens.d.ts
Add support for BACS Debit as a `PaymentMethod`
* Add `settings[bacs_debit_payments]` on `Account`
* Add `bacs_debit` as a `type` on `PaymentMethod` 
* Add `payment_method_details[bacs_debit]` on `Charge`
* Add `bacs_debit` on `Mandate`
Codegen for openapi 7a853ce
=> Add support for BACS Debit as a `PaymentMethod`

types/2020-03-02/Checkout/Sessions.d.ts
=> Add support for Bancontact, EPS, Giropay and P24 on Checkout `Session`

types/2020-03-02/Checkout/Sessions.d.ts, types/2020-03-02/Customers.d.ts, types/2020-03-02/InvoiceLineItems.d.ts, types/2020-03-02/Invoices.d.ts, types/2020-03-02/PaymentMethods.d.ts, types/2020-03-02/SubscriptionSchedules.d.ts, types/2020-03-02/TaxIds.d.ts
=> Add support for `id_npwp` and `my_frp` as `type` on `TaxId`

README.md, lib/stripe.js, test/stripe.spec.js
r? @ob-stripe 
Throws an exception when the stripe client is initialized if the `http` protocol is specified without configuring a non-stripe.com host.
Also documents the `protocol` configuration option.
Fixes https://github.com/stripe/stripe-node/pull/938
=> Document but discourage `protocol` config option

lib/stripe.js
r? @stripe/api-libraries
cc @stripe/api-libraries @remi-stripe @paulasjes-stripe 
This just surfaces the `StripeResource` on the instance as well, so you can continue to do `const stripe = require('stripe')(apiKeyHere);` but still be able to add resources while working with beta things.
=> Expose StripeResource on instance

types/OAuth.d.ts
The parameter is an [(optional) array of strings](https://stripe.com/docs/connect/express-accounts#specify-capabilities-for-an-account), not a string.  Fixes #944.
=> Fix `assert_capabilities` type definition

types/2020-03-02/Checkout/Sessions.d.ts, types/2020-03-02/LineItems.d.ts, types/2020-03-02/SubscriptionSchedules.d.ts
* Change from string to enum value for `billing_address_collection` on Checkout `Session`
=> Change from string to enum value for `billing_address_collection` on Checkout `Session`

types/2020-03-02/Checkout/Sessions.d.ts, types/2020-03-02/InvoiceLineItems.d.ts, types/2020-03-02/Invoices.d.ts, types/2020-03-02/LineItems.d.ts, types/2020-03-02/PaymentIntents.d.ts, types/2020-03-02/SetupIntents.d.ts, types/2020-03-02/SubscriptionItems.d.ts, types/2020-03-02/Subscriptions.d.ts, types/2020-03-02/TaxRates.d.ts
=> Add support for `amount_total`, `amount_subtotal` and `amount_details` on Checkout `Session`

lib/StripeResource.js, test/stripe.spec.js
r? @jlomas-stripe  
cc @stripe/api-libraries @brandur-stripe 
If any of these three fields are set in the headers, copy them over to lastResponse as suggested in #406.
Also add tests for the new fields and refactor an existing test for lastResponse.
=> Add new fields to lastResponse: apiVersion, stripeAccount, idempotencyKey

lib/StripeResource.js
Minor change, but the code below uses triple `=`, so might be worth cleaning this up
=> Use strict equality check for 'protocol' field for consistency

lib/Webhooks.js, lib/makeRequest.js, lib/utils.js, test/resources/BalanceTransactions.spec.js, test/utils.spec.js
Cleans up the remaining `var` usages and converts them to `let/const` usages. 
Let me know if you can find any other `var`s and I will update the pull request. Thanks!
=> Refactor remaining 'var' to 'let/const' usages

types/2020-03-02/Accounts.d.ts, types/2020-03-02/Persons.d.ts, types/2020-03-02/Tokens.d.ts
=> Add support for `political_exposure` on `Person`

types/2020-03-02/Accounts.d.ts
=> Add support for `capabilities` as a parameter on `Account` create and update

types/2020-03-02/Accounts.d.ts, types/2020-03-02/SubscriptionSchedules.d.ts
=> Add support for `cartes_bancaires_payments` as a `Capability`

types/2020-03-02/Accounts.d.ts, types/2020-03-02/Checkout/Sessions.d.ts, types/2020-03-02/Customers.d.ts, types/2020-03-02/Discounts.d.ts, types/2020-03-02/InvoiceItems.d.ts, types/2020-03-02/InvoiceLineItems.d.ts, types/2020-03-02/Invoices.d.ts, types/2020-03-02/PaymentIntents.d.ts, types/2020-03-02/PaymentMethods.d.ts, types/2020-03-02/Plans.d.ts, types/2020-03-02/PromotionCodes.d.ts, types/2020-03-02/SubscriptionItems.d.ts, types/2020-03-02/SubscriptionSchedules.d.ts, types/2020-03-02/Subscriptions.d.ts, types/2020-03-02/TaxIds.d.ts
=> Add support for Alipay on `PaymentMethod` and `PaymentIntent`

types/2020-03-02/Charges.d.ts, types/2020-03-02/Issuing/Disputes.d.ts
r? @richardm-stripe (feel free to change reviewer)
* Added support for `bank_name` on `Charge.payment_method_details.acss_debit`
* `Issuing.dispute.balance_transactions` is now nullable.
=> [codegen] Multiple API Changes

types/2020-03-02/Customers.d.ts, types/2020-03-02/Issuing/Authorizations.d.ts, types/2020-03-02/Issuing/Transactions.d.ts
=> Add support for `amount_details` on Issuing `Authorization` and `Transaction`

types/2020-08-27/Cards.d.ts, types/2020-08-27/Charges.d.ts, types/2020-08-27/Checkout/Sessions.d.ts, types/2020-08-27/PaymentIntents.d.ts, types/2020-08-27/PaymentMethods.d.ts
=> Add support for Sofort on `PaymentMethod` and `PaymentIntent`

types/2020-08-27/index.d.ts, types/lib.d.ts, types/test/typescriptTest.ts
Fixes https://github.com/stripe/stripe-node/issues/994
r? @jlomas-stripe 
We considered adding this for https://github.com/stripe/stripe-node/pull/920 but then opted not to, but per #994 this is not convenient for users. We could just expose `any` but why not try and get the types right?
The types in this PR are an approximation that reflect mostly the "public interface" of Stripe.StripeResource, and still use `any` a great deal, but it's a starting place.
=> Typedef for Stripe.StripeResource

types/2020-08-27/FileLinks.d.ts, types/2020-08-27/Payouts.d.ts
Changes `FileLinkUpdateParams.expires_at^ to be "nullable" rather than "emptyStringable".
stripe-node converts nulls to empty strings before sending over the wire (urlencoded has no concept of 'null'), and using null is a more idiomatic way of "unsetting" a property so our convention for these type bindings is to provide null instead of empty string, but up till now our codegen infrastructure wasn't property handling this case before since it got confused by the presence of "now".
=> More idiomatic types

types/2020-08-27/PaymentMethods.d.ts
=> Add support for `oxxo` as a valid `type` on the List PaymentMethod API

types/2020-08-27/Accounts.d.ts, types/2020-08-27/PaymentIntents.d.ts
=> Add support for `oxxo_payments` capability on `Account`

types/2020-08-27/Reporting/ReportRuns.d.ts
=> Add support for `contribution` in `reporting_category` on `ReportRun`

lib/resources.js, lib/resources/SetupAttempts.js, test/resources/SetupAttempts.spec.js, types/2020-08-27/SetupAttempts.d.ts, types/2020-08-27/SetupIntents.d.ts, types/2020-08-27/index.d.ts
=> Add support for the `SetupAttempt` resource and List API

types/2020-08-27/Accounts.d.ts, types/2020-08-27/Charges.d.ts, types/2020-08-27/CustomerBalanceTransactions.d.ts, types/2020-08-27/Customers.d.ts
=> Add support for new payments capabilities on `Account`

types/2020-08-27/CreditNoteLineItems.d.ts, types/2020-08-27/CreditNotes.d.ts, types/2020-08-27/Discounts.d.ts, types/2020-08-27/InvoiceItems.d.ts, types/2020-08-27/InvoiceLineItems.d.ts, types/2020-08-27/Invoices.d.ts
Updates the type bindings for several discount-related fields to indicate that these fields will now always be present.
=> Update Typescript types

types/2020-08-27/Cards.d.ts, types/2020-08-27/Charges.d.ts, types/2020-08-27/PaymentMethods.d.ts
=> Add support for `description`, `iin` and `issuer` in `payment_method_details[card_present]` and `payment_method_details[interac_present]` on `Charge`

lib/utils.js, test/makeRequest.spec.js
When a user supplies opts to a function, the user's opts are mutated. This becomes a problem when a user supplies an opt that is deprecated; e.g. `stripe_account` instead of `stripeAccount`. In this scenario:
- Before calling the function:
```javascript
opts = {
...
stripe_account: ...,  // user supplies a deprecated opt
...
}
```
- After calling the function, the object is mutated:
```javascript
opts = {
...
stripe_account: ...,
stripeAccount: ...,  // the function unexpectedly inserts the non-deprecated version of the opt
...
}
```
Because of this mutation, the user is warned that they have supplied both of these args, when in fact they have only supplied one.
This change makes a shallow copy of the user's opts so that this does not happen.
fixes …
=> Do not mutate user-supplied opts

types/2020-08-27/Checkout/Sessions.d.ts
Codegen for openapi aacc1c6.
r? @remi-stripe
* Added support for `discounts` on `session.create`
=> Typescript: Add support for `discounts` on `Session.create`

types/2020-08-27/Payouts.d.ts
=> Make `original_payout` and `reversed_by` not optional anymore

.vscode/extensions.json
Sublime Babel which is no longer available on the vscode marketplace and we get below message when trying to open project in vscode.
Babel Javascript is well maintained alternative.
[differences](https://github.com/michaelgmcd/vscode-language-babel/issues/1)
=> chore: replace recommended extension sublime babel with babel javascript

types/2020-08-27/Checkout/Sessions.d.ts, types/2020-08-27/Customers.d.ts, types/2020-08-27/Invoices.d.ts, types/2020-08-27/TaxIds.d.ts
=> Add support for `jp_rn` and `ru_kpp` as a `type` on `TaxId`

types/2020-08-27/Cards.d.ts, types/2020-08-27/Charges.d.ts, types/2020-08-27/PaymentMethods.d.ts, types/2020-08-27/SubscriptionSchedules.d.ts, types/2020-08-27/Subscriptions.d.ts
=> Support passing `tax_rates` when creating invoice items through `Subscription` or `SubscriptionSchedule`

types/lib.d.ts
r? @suz-stripe 
Defines `Stripe.Emptyable<T> = null | '' | T` type. Many params in the Stripe API has a "pass empty string to unset" idiom, and stripe-node converts nulls to empty strings over the wire. Presently, the type bindings encode all of these as `T | null`, but this [is a bit confusing](https://github.com/stripe/stripe-node/issues/1051) because some of the docstrings recommend empty strings.
I think adding an "Emptyable" wrapper like this will make the meaning of these type definitions a little bit more clear, and it also gives us a single place where we can document this behavior.
In VSCode, the present mouseover looks like
and the new one will be this:
It seems like VSCode omits mention of `| null` altogether, so the new mouseover is the only one that …
=> Add Stripe.Emptyable type definition

README.md
README now clearly states which versions of Node are supported.
My IDE also automagically cleaned up the table formatting.
=> Added requirements to README

types/2020-08-27/Charges.d.ts, types/2020-08-27/PaymentIntents.d.ts
This PR adds support for `payment_method_details[interac_present][preferred_locales]` on `Charge`. It also adds an empty-able hash `payment_method_options[p24]` on `PaymentIntent` for an upcoming feature but this change is a no op
Codegen for openapi 9f2a7bc
=> Add  `payment_method_details[interac_present][preferred_locales]` on `Charge`

lib/resources/Accounts.js, lib/resources/ApplicationFees.js, lib/resources/Customers.js, lib/resources/Transfers.js, types/2020-08-27/Accounts.d.ts, types/2020-08-27/Checkout/Sessions.d.ts, types/2020-08-27/Files.d.ts, types/2020-08-27/Issuing/Authorizations.d.ts
=> Add support for `documents` on `Account` create and update

types/2020-08-27/Accounts.d.ts, types/2020-08-27/Invoices.d.ts
Codegen for openapi 383c876.
* Added support for `company_registration_verification`, `company_ministerial_decree`, `company_memorandum_of_association`, `company_license` and `company_tax_id_verification` on `AccountUpdateParams.documents` and `AccountCreateParams.documents`
=> API Updates

types/2020-08-27/Customers.d.ts, types/2020-08-27/Refunds.d.ts
r? @stripe/api-library-reviewers 
A change in our codegen infra revealed a few inconsistencies/bugs in the Typescript definitions. This PR resolves those.
1. `CustomerSource` is now qualified as `Stripe.CustomerSource` inside `Customers.d.ts`, which is more consistent with similar references. This is a no-op. 
2. Extra method definitions have been removed from `Refund.d.ts`. This is a bug fix. The cause of this was that the openapi spec defines methods for both `/v1/refunds/{refund}` and `/v1/charges/{charge}/refunds/{refund}`. However, the actual Javascript code in `refunds.js` only supports making requests to the `/v1/refunds/{refund}` routes, so I have removed the extra type definitions because they are incorrect and do not describe valid uses of the library.
3. The type definition of …
=> More consistent type definitions

lib/StripeResource.js, test/StripeResource.spec.js, testUtils/index.js
fixes #1058
r? @tjfontaine-stripe @ctrudeau-stripe 
Presently errors that result from the node http request timeout [are not eligible to be retried](https://github.com/stripe/stripe-node/compare/richardm-retry-request-timeouts?expand=1#diff-d5d3bf39549deedcf2b6f61e2f2f7f8398c71b21ba178612e0ff5c81a06d1ce5L227-L231).
I doubt this is deliberate and it seems like these requests should generally be retried, the same as ECONNRESET or any other sort of connection error.
This is technically a behavior change, so my inclination is to wait until the next major version, since there are a lot of open network-related issues and it would be good to address several of them.
=> make request timeout errors eligible for retry

types/2020-08-27/Accounts.d.ts
Fixes #1002, #879.
Reflects changes I've made upstream to the system that generates this code, based off of our docs at https://stripe.com/docs/api/accounts/create#create_account-external_account.
Slightly different from #1002, namely `account_number`, plus alphabetization.
=> Better type for `AccountCreateParams.external_account`

examples/webhook-signing/node-express/express.js, examples/webhook-signing/typescript-node-express/express-ts.ts
In express 4.16+, bodyParser is now accessible through the `express` module directly: https://stackoverflow.com/questions/66525078/bodyparser-is-deprecated
Tada!
Thanks!
=> Remove deprecated bodyParser dep in webhook examples

.travis.yml, package.json, yarn.lock
This PR bumps some devDependencies that are marked as vulnerable. This is merely for hygiene: the vulnerabilities do not affect this library -- we do not rely on the vulnerable code paths, nor does the development workflow involve live traffic.
The upgraded dependencies are not compatible with Node 8, and so this PR also disables Node 8 in CI. We hope to officially deprecate Node 8 soon, but in the meantime we will be not be able to rely on CI to be sure Node 8 does not break and should verify that any potentially incompatible changes are tested manually.
r? @stripe/api-library-reviewers
=> Upgrade devDependencies

README.md
Webhook signatures are documented on their own page now. This PR updates a README link to reflect that.
=> Fix webhook signatures docs link

lib/StripeResource.js, lib/makeRequest.js, lib/utils.js, test/StripeResource.spec.js, testUtils/index.js
r? @dcr-stripe 
cc @stripe/api-libraries  
This PR adds support for defining 'streaming' stripe methods on the Stripe client.  Unlike existing methods, 'streaming' methods do not buffer the response body into memory and try to parse it into json -- they pass the underlying `http.Request` object to the caller, so that the caller can pipe it to a file or socket without having to buffer it.
The motivation for this is an upcoming `/pdf` method that will return a pdf instead of JSON.
Also incidentally adds the ability to set "host" per-request, this was useful in my testing.
=> Binary streaming

lib/StripeResource.js, types/lib.d.ts
r? @dcr-stripe 
Contains two changes that should have been in #1157 but were not.
1. Successful HTTP requests are those with status codes *strictly less* than 400, not `<=` 400. Luckily I made a bad request while testing and caught this.
2. Expose a `StripeStreamResponse` typescript type to describe the return types of binary streaming methods.
=> Streaming method support fixes

README.md
Links to Stripe.js documentation are outdated.
=> Update links to Stripe.js docs

lib/StripeResource.js, lib/stripe.js, types/lib.d.ts
This is a pretty minor code change allowing a new option in the StripeConfig interface **stripeAccount**
When building an API request, the Stripe-Account header is now added to the default request headers.
=> #857 Allow default stripeAccount in options

lib/StripeResource.js, lib/stripe.js, test/stripe.spec.js, testUtils/index.js, types/lib.d.ts
r? @stripe/api-library-reviewers 
Adds a test on top of user @lyndonbuckley's contribution #1102 (which I will merge first), to let stripeAccount be settable when initializing the stripe client, plus a test.
=> Test for global `stripeAccount`

lib/autoPagination.js
- error constructor takes 0..1 arguments
- use style from https://github.com/stripe/stripe-node/blob/7d30a6a20b778d95cf9f65e800c1544be5208bcf/lib/autoPagination.js#L125-L129
=> fix error arguments

lib/StripeMethod.js, lib/makeRequest.js, test/StripeResource.spec.js, test/makeRequest.spec.js, types/lib.d.ts, types/test/typescriptTest.ts
Adds support for `fullPath` to StripeMethod, letting methods specify a full path (ie. a path that is not a suffix of the resource base).
This is necessary for search URLs and in the future we plan on migrating all methods to this, removing some of the URL magic behind the scenes.
Added unit tests.
=> Add support for fullPath on methods.

lib/stripe.js, test/stripe.spec.js
r? @dcr-stripe 
Fixes https://github.com/stripe/stripe-node/issues/1202
Right now, when calculating the proper user agent, we check a cache and shell out to `uname` if the cache is empty. This is bad because we can shell out to `uname` multiple times concurrently before the cache is populated. For some bulk operation usage patterns this causes an unwanted CPU spike (see #1202). It would be better to only shell out once.
This PR makes two changes:
1. Makes the cache use a promise. Promises are very good at resolving a value only once.
2. Caches the result of `uname` directly, instead of the derived `user_agent`. This allows me to remove some questionable cache invalidation. We should only ever need to call `uname` once, `uname` is not expected to change.
**Breakingness:** …
=> Prevent fetching the user agent concurrently

test/stripe.spec.js, types/lib.d.ts, types/test/typescriptTest.ts
Move typescript definition for `headers` to the correct location. 
You can see that they are added to the object that eventually becomes `.lastResponse` [here](https://github.com/stripe/stripe-node/blob/master/lib/StripeResource.js#L174)
Fixes https://github.com/stripe/stripe-node/issues/1204
=> Fix Typescript definition for `StripeResource.LastResponse.headers`

lib/StripeResource.js, lib/net/HttpClient.js, lib/net/NodeHttpClient.js, lib/stripe.js, test/StripeResource.spec.js, test/net/NodeHttpClient.spec.js, test/stripe.spec.js, testUtils/index.js, types/2020-08-27/index.d.ts, types/lib.d.ts, types/net/net.d.ts, types/test/typescriptTest.ts
r? @richardm-stripe + @tjfontaine-stripe (for extra 👀 )
Adds an `HttpClient` interface and moves out the Node `http`/`https` request logic into a `NodeHttpClient` implementation. Update Stripe config to allow specifying a custom `HttpClient`.
This is the first step in allowing a custom client (say one that uses fetch for https://github.com/stripe/stripe-node/issues/997).
The interface is summarized in the typescript. In brief:
- `makeRequest` returns a `Response` as a promise.
- `Response#toStream(streamCompleteCallback)` returns a streamable version of the content. The Node behavior is unchanged here of just returning the raw response itself with the headers tacked on.
- `Response#toJSON()` consumes the response and returns the JSON representation as a promise.
This should effectively be …
=> Add an HttpClient interface and NodeHttpClient implementation.

lib/stripe.js, lib/utils.js, test/stripe.spec.js
Updates the user agent computation to handle JS environments which don't have a global `process` variable (eg. browser, Cloudflare Worker). This moves towards unblocking https://github.com/stripe/stripe-node/issues/997.
=> Update user agent computation to handle environments without process.

lib/net/HttpClient.js, lib/net/NodeHttpClient.js, lib/stripe.js, test/stripe.spec.js, types/net/net.d.ts
Adds a client name property to be implemented by `HttpClient` which will be shipped in the user agent under the `httplib` property similar to Python.
=> Add client name property to HttpClient.

lib/StripeMethod.js, lib/autoPagination.js, test/autoPagination.spec.js, types/lib.d.ts, types/test/typescriptTest.ts
Adds support for search methods and `search_result` objects returned by the Stripe API. This requires updating auto pagination to support this. These paginate similarly to lists, however they rely on a `next_page` token included in the response rather than using object IDs + `starting_before`/`ending_after`. Thus, only forward pagination is supported
Added unit tests. We'll want to add some more rigorous tests once a resource is using this.
=> Add support for SearchResult.

types/2020-08-27/Checkout/Sessions.d.ts
`CheckoutSession.AfterExpiration.Recovery.allow_promotion_codes` and `CheckoutSession.AfterExpiration.Recovery.enabled` will always be present. This PR changes the typescript bindings to reflect this.
=> Typescript: better types for non-optional CheckoutSession fields

.eslintrc.js, lib/net/FetchHttpClient.js, lib/net/HttpClient.js, lib/net/NodeHttpClient.js, package.json, test/net/FetchHttpClient.spec.js, test/net/helpers.js, yarn.lock
Adds an `HttpClient` implementation that uses the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API).
This paves the way for unblocking https://github.com/stripe/stripe-node/issues/997.
The common tests are shared between NodeHttpClient and FetchHttpClient to make sure both meet the requirements for the interface (modulo some streaming/raw response tests, as this is implementation-dependant). In order to test `fetch` as part of our Node testing environment, the [node-fetch](https://www.npmjs.com/package/node-fetch) polyfill is used.
=> Add an HTTP client which uses fetch.

test/net/FetchHttpClient.spec.js, test/net/NodeHttpClient.spec.js, test/net/helpers.js
Removes the `httpClientName` param from `createHttpClientTestSuite`. This isn't necessary and callers can just wrap the all in a describe as needed.
=> Remove client name param from createHttpClientTestSuite.

lib/Webhooks.js, lib/crypto/CryptoProvider.js, lib/crypto/NodeCryptoProvider.js, lib/stripe.js, test/Webhook.spec.js, test/crypto/NodeCryptoProvider.spec.js, test/crypto/helpers.js, testUtils/index.js, types/2020-08-27/index.d.ts, types/Webhooks.d.ts, types/crypto/crypto.d.ts
Adds an `CryptoProvider` interface and moves out the Node `crypto` logic into a `NodeCryptoProvider` implementation. 
This initially only supports computing HMAC signatures, but lets us support this in a pluggable way. The Webhooks functions are updated to support passing in a custom provider. This can be used in environments where no 'crypto' package is available (removing another Node dependency for https://github.com/stripe/stripe-node/issues/997).
Added a small common set of test cases which can be re-used by any implementation to ensure they meet the contract.
Some crypto APIs (eg. the [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API)) only provide async functions for computing HMACs (and other primitives). In the future, we may …
=> Add a CryptoProvider interface and NodeCryptoProvider implementation.

.github/workflows/main.yml, README.md, test/resources/Integration.spec.js, testUtils/index.js
Adds support for `stripe-mock` tests by running the Docker image as part of CI and adding utility functions for creating a stripe-mock client.
Added a sample integration test which uses this client.
=> Add stripe-mock for testing along with a sample integration test.

types/lib.d.ts, types/test/typescriptTest.ts
I have access to a beta feature, which I wanted to use with the stripe library. 
In the process, I found that the result of `Stripe.StripeResource.extend()` did not have a constructor, so TypeScript would not let you do this:
```ts
const Foo = Stripe.StripeResource.extend(); 
new Foo(stripe)
```
This fixes that.
For context, I use this like so:
```ts
class Foos extends Stripe.StripeResource.extend({ path: "foos" }) {
create = Stripe.StripeResource.method({ method: "POST", path: "" }) as (
params: Stripe.FooBetaFeatureCreateParams,
options: Stripe.RequestOptions
) => Promise<Stripe.Response<Stripe.FooBetaFeature>>;
update = Stripe.StripeResource.method({ method: "POST", path: "/{foo}" }) as (
id: string,
params: Stripe.FooBetaFeatureUpdateParams,
options: Stripe.RequestOptions
) => …
```
=> Fix StripeResource.extend type

examples/webhook-signing/README.md
Updating link to Stripe Samples to point at a new sample instead of the archived one.
=> Update link from archived sample to new sample

lib/net/FetchHttpClient.js
cc? @tomer-stripe 
Updates the `FetchHttpClient` to make the `fetch` function optional, defaulting to the global if not provided. 
This also purposefully avoids calling `this._fetchFn()` directly and instead storing it and calling it via the variable. This ensures we call the passed in function with the global scope instead of accidentally calling it with the `FetchHttpClient` as `this`. Calling `this._fetchFn()` caused issues on Cloudflare Workers as it would invoke `fetch` in the wrong scope, resulting in code failing with:
> A hanging Promise was canceled. This happens when the worker runtime is waiting for a Promise from JavaScript to resolve, but has detected that the Promise cannot possibly ever resolve because all code and events related to the Promise's …
=> Update FetchHttpClient to make fetch function optional.

package.json, yarn.lock
Updates the `ansi-regex` dependency version to 5.0.1.
Unfortunately we have to do this as a manual hard-coded resolution as not all underlying packages point to this even on their latest versions + this would require upgrading eslint and we have some linting errors on the latest version.
=> Bump up ansi-regex version to 5.0.1.

.github/workflows/main.yml, package.json, test/.mocharc.js, test/mocha.opts, test/net/NodeHttpClient.spec.js
Replaces the mocha.opts file with a new Mocha configuration file. The mocha.opts file was deprecated and removed entirely in Mocha v8 ([CHANGELOG](https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#800--2020-06-10)). The end result is that after we upgraded from Mocha 6 to 8 we were no longer running Mocha with `--recursive` and were only running a subset of our tests. 
I also added the [new `--parallel` option](https://mochajs.org/#parallel-tests) here, which runs tests in parallel and speeds up our test suite (locally it's going from ~70-80s -> 35s).
To get tests to pass I had to update:
1. the stripe-mock Docker image, which was stale
2. a broken require in the NodeHttpClient test 
See CI.
=> Replace unused mocha.opts with Mocha configuration file.

test/autoPagination.spec.js, testUtils/index.js
Removes the `envSupportsAwait` test util, as this was only needed for versions of Node prior to 8. We only officially support and test against 8+ so this is no longer necessary.
Tests pass.
=> Remove stale test util for detecting await support.

types/lib.d.ts, types/test/typescriptTest.ts
This improves three friction points when working with Typescript:
1. **`new StripeResource(stripe)` now works.** Prior to this change, attempting to construct `StripeResource` with its one required argument would fail a type check. Support for a constructor was added in #1245 and extended in #1249 (never merged). Thanks @rattrayalex!
2. **`StripeResource.extend` now returns a class that is properly typed when instantiated.** Prior to this change, you could extend `StripeResource` but your extensions wouldn't appear on the object after construction. Now, it does.
3. **`StripeResource.method` returns a function that returns `Response<object>`.** Prior to this change, extensions created with `StripeResource.method` would have a return type of `object`. Returning …
=> Improve typescript support

lib/Webhooks.js, lib/crypto/CryptoProvider.js, lib/crypto/NodeCryptoProvider.js, lib/crypto/SubtleCryptoProvider.js, lib/stripe.js, test/Webhook.spec.js, test/crypto/SubtleCryptoProvider.spec.js, test/crypto/helpers.js, testUtils/index.js, types/Webhooks.d.ts, types/crypto/crypto.d.ts, types/test/typescriptTest.ts
Introduce a new `CryptoProvider` which uses the [`SubtleCrypto` API](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/). This is the main implementation for the [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API).
This requires adding support for async HMAC computations in `CryptoProvider` and adding new async Webhook creation/verification functions which can use these.
As a result, we can now construct and verify a webhook asynchronously by doing:
```
const cryptoProvider = Stripe.createSubtleCryptoProvider();
const event = await stripe.webhooks.constructEventAsync(
body, 
signature, 
secret,
tolerance, 
cryptoProvider
);
```
I opted to go down the route of having sync and async methods rather than parameterizing the …
=> Add SubtleCryptoProvider and update Webhooks to allow async crypto.

README.md, package.json, yarn.lock
r? @stripe/api-library-reviewers 
Context: we haven't been triggering coveralls in our CI since June, when we switched to Github Actions. We hadn't really been acting on any insights from it and it was more trouble than it was worth.
Still, it's been hanging out in our devDependencies. Dependabot today is [warning](https://github.com/stripe/stripe-node/security/dependabot/yarn.lock/json-schema/open) about one of coveralls transitive dependencies, so to fix it, I prepared this PR to excise coveralls from our codebase entirely.
=> Remove coveralls from package.json

types/net/net.d.ts
Adds a comment documenting why `HttpClient#makeRequest(headers)` doesn't use a stricter type. Unfortunately this is implementation-specific and enforcing a stricter type could break some integrations.
As examples, we cannot just use `{[key: string]: string}` since:
1. Node actually supports `{[key: string]: string | number | string[]}`
2. Fetch actually also supports `string[][]` as well as a `Headers` object.
=> Add comment documenting makeRequest#headers type.

types/crypto/crypto.d.ts, types/net/net.d.ts, types/test/typescriptTest.ts
Removes the references to DOM types, specifically the fetch function (and its return/stream types) as well as the SubtleCrypto interface.
Unfortunately this reference pollutes the global namespace for Node packages, which don't include these DOM APIs.
We lose some type-safety here by switching to `any` but the alternative would be copying in the types from the DOM typescript definitions. These are quite substantial (eg. the `fetch` input arguments require many types) and would require keeping these types in sync with moving web standards.
https://github.com/stripe/stripe-node/issues/1326
=> Remove DOM type references.

types/2020-08-27/Customers.d.ts
According to the documentation https://stripe.com/docs/api/customers/object#customer_object-tax_ids
> This field is not included by default.
Typing suppose it is.
Doing `stripe.customers.retrieve` show it is indeed not included by default.
=> Customer tax_ids is not included by default

lib/StripeResource.js, test/StripeResource.spec.js
Custom request timeout message was never used since we were incorrectly
requiring the HttpClient class.
I believe this has stopped working on #1218.
=> fix(http-client): use named import

package.json, yarn.lock
Bump nanoid from 3.1.20 to 3.2.0. I had to pin it via `resolutions` due to our Mocha dep. Unfortunately this dependency was only changed in Mocha 9+, which we can't currently update to as it no longer supports Node 10 (https://github.com/mochajs/mocha/blob/master/CHANGELOG.md#boom-breaking-changes).
[CVE-2021-23566](https://github.com/advisories/GHSA-qrpm-p2h7-hrv2)
=> Bump nanoid from 3.1.20 to 3.2.0.

lib/Error.js, test/Error.spec.js
When the API returns an error of a type which isn't explicitly enumerated, `StripeError.generate` tries to return a `GenericError`. However, that class doesn't exist - it was deleted as part of the refactor in https://github.com/stripe/stripe-node/pull/672. This causes stripe-node to return an especially confusing error - it complains about the undefined `GenericError` class, instead of telling us anything useful about the actual error.
This patch defines a fallback subclass of StripeError to use in these cases. (As a bonus, this means that the default error rendering will also contain the error message from the API, instead of a fixed `Unknown Error` string.)
AFAICT, the only way it was possible to hit this branch is to get the oauth flow to return weird errors. Since this is served from …
=> Properly handle API errors with unknown error types

README.md
This request updates the documentation to use the correct way to send appInfo, taken from the PR found [here](https://github.com/stripe/stripe-node/pull/752#issue-547115745): 
The current documentation references a deprecated method `stripe.setAppInfo({})` for setting appInfo on requests.  Using the current documentation results in this error:
```
stripe.appInfo({
^
TypeError: stripe.appInfo is not a function
at Object.<anonymous> (/Users/caranda/Documents/Ignitio/repositories/stripe-collector/index.js:7:8)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
at Module.load (node:internal/modules/cjs/loader:981:32)
at Function.Module._load (node:internal/modules/cjs/loader:822:12)
at …
```
=> update documentation to use appInfo

types/lib.d.ts
add ts declaration for `onDone` callback parameter on `autoPagingEach` and `autoPagingToArray`
as implemented:
- https://github.com/stripe/stripe-node/blob/ec960ead66f9942d68804f1a91dce8988d8d9660/lib/autoPagination.js#L170
- https://github.com/stripe/stripe-node/blob/ec960ead66f9942d68804f1a91dce8988d8d9660/lib/autoPagination.js#L187
=> ts declaration for onDone on autoPagingEach and autoPagingToArray

lib/autoPagination.js, test/autoPagination.spec.js, types/lib.d.ts
Updates the search pagination behavior to account for two changes:
1. The `next_page` request parameter has been renamed to `page`.
2. The `next_page` response property is always provided, but will return null when there is no page. Previously it would not be provided in the return object at all.
This is not considered a breaking change as no currently released API uses this object and is thus purely an infrastructural change.
=> Update search pagination to use page param instead of next_page.

package.json, yarn.lock
Bumps [minimist](https://github.com/substack/minimist)[](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)[](https://github.com/apps/dependabot)[](https://github.com/apps/dependabot)[](https://github.com/apps/github-actions)[](https://github.com/apps/github-actions)[](https://github.com/apps/github-actions)[](https://github.com/apps/github-actions)[](https://stripe.com/)[](https://cla-assistant.io/)[](https://stripe.com/)[](https://stripe.com/)[](https://github.com/kamil-stripe)[](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)[](https://github.com/) from 1.2.5 to 1.2.6.
Affected versions of this package are vulnerable …
=> Force update minimist dependency

lib/StripeResource.js, test/StripeResource.spec.js
r? @pakrym-stripe 
Stops sending a `Content-Length` header for requests which:
1. Use a verb which doesn't anticipate a body (eg. `GET`, `DELETE`) and
2. Actually has no body.
For requests that don't anticipate a body but end up having one, we'll continue setting the header and emit a warning so that we can track and fix these cases as they are not following proper semantics.
`POST`, `PUT` and `PATCH` request are unchanged.
Fixes https://github.com/stripe/stripe-node/issues/1360
=> Stop sending Content-Length header for verbs which don't have bodies.

.github/workflows/main.yml, package.json
Split CI into build stage that builds and lints on the latest Node.js and test stage that tests on each Node.js version that is supported by us.
=> Split CI into two stages

test/StripeResource.spec.js
Adds tests which capture two behaviors when specifying a custom host for a `StripeMethod`:
1. It takes precedence over the global host.
2. It can be overridden on a per-request basis.
=> Add tests for specifying a custom host on StripeMethod.

.github/workflows/main.yml
Use `npm config` set to set the token value and `npm whoami` to verify that login was successfull.
Also wait for tests to be done before publishing
=> Use npm config to set a token value

lib/net/HttpClient.js
r? @kamil-stripe  
Updates the documentation for HttpClient now that it is stable and used by both `NodeHttpClient` and `FetchHttpClient` in production. This is no longer experimental.
=> docs: Update HttpClient documentation to remove experimental status.

test/StripeResource.spec.js, types/lib.d.ts, types/test/typescriptTest.ts
Fixes https://github.com/stripe/stripe-node/issues/1447
r? @pakrym-stripe
=> Add types for extra request options

.github/workflows/main.yml
We don't want beta version to be installed by default when someone calls `npm install stripe`. Publish beta versions to the beta tag instead.
=> Only publish stable version to the latest tag

CHANGELOG.md, Makefile
While reviewing https://github.com/stripe/stripe-node/pull/1451 I've noticed that some entries were removed because they don't follow our changelog spec. Fix those and backport the https://github.com/stripe/stripe-node/pull/1445 to master.
r? @kamil-stripe
=> Fix non-conforming changelog entries and port the Makefile fix

package.json, yarn.lock
=> Move @types/node to devDependencies

lib/StripeResource.js, lib/makeRequest.js, test/StripeResource.spec.js
Fixes URL creation to include a trailing slash for endpoints which should have a query parameter (eg. `/v1/customers/{id}`) to avoid using `/v1/customers` as the endpoint instead of `/v1/customers/` when an empty ID parameter is passed.
The server interprets these differently based on whether the trailing slash is present.
=> fix: Include trailing slash when passing empty query parameters.

types/2022-08-01/Accounts.d.ts, types/2022-08-01/Charges.d.ts, types/2022-08-01/Checkout/Sessions.d.ts, types/2022-08-01/CustomerSources.d.ts, types/2022-08-01/Customers.d.ts, types/2022-08-01/Invoices.d.ts, types/2022-08-01/Orders.d.ts, types/2022-08-01/PaymentIntents.d.ts, types/2022-08-01/PaymentMethods.d.ts, types/2022-08-01/Persons.d.ts, types/2022-08-01/SetupIntents.d.ts, types/2022-08-01/Sources.d.ts, types/2022-08-01/Terminal/Locations.d.ts, types/2022-08-01/Terminal/Readers.d.ts, types/2022-08-01/Tokens.d.ts, types/2022-08-01/Treasury/OutboundPayments.d.ts, types/shared.d.ts
r? @pakrym-stripe 
- Rename `AddressParam` to `ShippingAddressParam`: shipping address is the only address that requires `line1`
- Rename `AccountAddressParam` to `AddressParam`: `AccountAddressParam` was not referenced
- Change instances of `Address extends Omit<ShippingAddressParam, "line1"> {line1?: string}` to `AddressParam`, which is the same type, and more concise
- Rename `AddressParam` to `ShippingAddressParam`, and change type of `Source.source_order.shipping.address`, `SourceUpdateParams.SourceOrder.Shipping.address`, and `SessionCreateParams.PaymentIntentData.Shipping.address` to `ShippingAddressParam`
- Rename `AccountAddressParam` go `AddressParam`, and change type of `AccountCreateParams.BusinessProfile.support_address`, …
=> Simplify AddressParam definitions

lib/net/FetchHttpClient.js, test/net/FetchHttpClient.spec.js
Updates the FetchHttpClient to explicitly send an empty string for methods which expect a payload but have no request data. 
https://github.com/stripe/stripe-node/issues/1519
Deno injects a second `Content-Length` header when we don't specify body explicitly (ie. pass a concrete value other than undefined), causing Stripe POST requests without bodies to fail. By passing an explicit body, this will no longer happen.
Publish this as a beta to validate the fix and then, if all looks good, roll it out to stable.
=> fix: Update FetchHttpClient to send empty string for empty POST/PUT/PATCH requests.

.github/workflows/main.yml, README.md, package.json
Add coveralls CI step. Test coverage data will be published to https://coveralls.io/github/stripe/stripe-node and displayed as a badge in the README.
=> Add test coverage using Coveralls

.eslintrc.js, src/Error.ts, src/StripeMethod.ts, src/StripeResource.ts, src/autoPagination.ts, src/makeRequest.ts, src/stripe.ts, tsconfig.json
Convert the following files to Typescript:
* StripeMethod
* StripeResource
* autoPagination
* makeRequest
* stripe
* Error
Validated that changes build and pass existing tests. Checked that transpiled JS files look functionally identical to the original JS. No observed changes in behavior when the library is imported and used in an external project.
=> Migrate Stripe infrastructure to Typescript

Makefile
r? @pakrym-stripe 
Add yarn build call at the end of codegen-format to restore lib/ after generating files.
=> Restore lib after generating

lib/Error.js, lib/Webhooks.js, src/Error.ts, src/Webhooks.ts
Splits detail field in `Webhooks.ts` to match the [convention for the same error in stripe-php](https://github.com/stripe/stripe-php/blob/c7cfc8bdf68f063cdd835f1fa9d6faa44b5cc8c3/lib/Exception/SignatureVerificationException.php#L23).
Remove `ts-expect-error` because `detail` is of type string.
=> Split StripeSignatureVerificationError detail field into header and payload

lib/utils.js, src/utils.ts, test/utils.spec.js
Fixes https://github.com/stripe/stripe-node/issues/1101 by using the native UUID implementation, if available. Added a (very) basic test as a starter.
=> use native UUID method if available

.github/workflows/main.yml
Do not run Coveralls step if the secret token does not exist (for pushes triggered by outside collaborators).
https://github.com/stripe/stripe-php/pull/1379 - make this change consistent across all languages
=> Do not run Coveralls if secret token is not available

lib/StripeMethod.js, lib/StripeResource.js, lib/makeRequest.js, lib/resources/OAuth.js, lib/stripe.js, src/StripeMethod.ts, src/StripeResource.ts, src/makeRequest.ts, src/resources/OAuth.js, src/stripe.ts, test/StripeResource.spec.js, types/test/typescriptTest.ts
* Reverts the [PR](https://github.com/stripe/stripe-node/pull/1604) that deprecated `path` on StripeResource and stripeMethod.
* Fixes the test suite not to depend on invoices defining `path`.
=> Don't deprecate relative `path`

lib/StripeResource.js, lib/stripe.js, src/StripeResource.ts, src/Types.d.ts, src/stripe.ts, tsconfig.json
I've noticed prototypes are not getting typed that hid a few issues.
=> Annotate prototypes with types

README.md
=> remove unneeded IIFE

types/Invoices.d.ts, types/InvoicesResource.d.ts, types/UpcomingInvoices.d.ts, types/index.d.ts, types/test/typescriptTest.ts
Fixes https://github.com/stripe/stripe-node/issues/1500.
Makes `stripe.invoices.retrieveUpcoming` return `Omit<Invoice, 'id'>` instead of `Invoice`. This means that `Invoice.id` can now be required and should prevent some needless null checks.
=> Narrower type for stripe.invoices.retrieveUpcoming()

package.json
Hey there!
Small fix for people using `{ "moduleResolution": "NodeNext" }` in their tsconfig
=> fix: added support for TypeScript "NodeNext" module resolution

lib/stripe.js, package.json, src/stripe.ts, test/RequestSender.spec.js, test/StripeResource.spec.js, test/flows.spec.ts, test/net/NodeHttpClient.spec.js, test/stripe.spec.ts, test/telemetry.spec.js, testUtils/index.js
Removes unnecessary entrypoint file `stripe.js`. Updates default entrypoint to be `stripe.node.js` in package.json and test imports.
=> Change default entrypoint to stripe.node

package.json
Fix for the `main` entrypoint on package.json.
Noticed it when ESLint was complaining about not being able to find the module on path since `11.9.0`.
=> Update main entrypoint on package.json

Makefile, scripts/updateAPIVersion.js
This fails because we re-arranged samples but we shouldn't update them automatically as they reference the package not the local code.
The misalignment will be caught by TS compiler when we update the package version used in tests.
=> Don't auto update api version in samples

README.md
This example never worked, the correct config property is `httpAgent`
=> Change httpProxy to httpAgent in README example

src/StripeMethod.ts, src/autoPagination.ts, test/autoPagination.spec.js
Refactors src/autoPagination.ts to create a clearer division between "define a .next() style iterator" step and "given an implementation of a .next()-style iterator, produce .autoPagingEach and .autoPagingToArray methods" step.
To me this makes this file more readable and easier to extend.
=> Refactor src/autoPagination.ts

src/stripe.core.ts, testProjects/mjs/index.js
* ⚠️ Removed `Stripe` and `default` circular properties on the Stripe object. This was added to maintain backwards compatibility during the transition of stripe-node to a dual ES module / CommonJS package, and should not be functionally necessary.
=> Remove circular reference in Stripe object

README.md, src/stripe.core.ts, test/stripe.spec.ts
**⚠️ ACTION REQUIRED: the breaking change in this release likely affects you ⚠️**
In this release, Stripe API Version `2022-11-15` (the latest at time of release) will be sent by default on all requests. 
The previous default was to use your [Stripe account's default API version](https://stripe.com/docs/development/dashboard/request-logs#view-your-default-api-version).
To successfully upgrade to stripe-node v12, you must either
1. **(Recommended) Upgrade your integration to be compatible with API Version `2022-11-15`.**
Please read the API Changelog carefully for each API Version from `2022-11-15` back to your [Stripe account's default API version](https://stripe.com/docs/development/dashboard/request-logs#view-your-default-api-version). Determine if you are using any of the APIs that …
=> Set the latest API version as the default

src/autoPagination.ts, test/autoPagination.spec.js
This is a follow-up to https://github.com/stripe/stripe-node/pull/1739#discussion_r1156111671.
I was originally going to make the iterator return `{done: true}` instead of `{done: true, value: undefined}` (which would have been a breaking change), but it turns out that `value: undefined` is actually the standard:
```node
> [][Symbol.iterator]().next()
{ value: undefined, done: true }
```
And it turns out that we can use the standard Typescript types for iterators/async iterators instead of defining our own. https://github.com/microsoft/TypeScript/blob/main/src/lib/es2015.iterable.d.ts#L11-L28 
Doing this is nonbreaking.
=> Use standard Typescript AsyncIterator types

test/Integration.spec.ts
Next.js dropped support for Node.js <16 in https://github.com/vercel/next.js/releases/tag/v13.3.2
=> Skip Next.js webhook sample test if Node version <16

src/Webhooks.ts, test/Webhook.spec.ts, types/Webhooks.d.ts
Lets you supply an optional timestamp to Webhook.constructEvent (and all intermediate functions) to use instead of `Date.now()` when verifying webhook signatures.
Fixes #1778
=> Let user supply a timestamp when verifying webhooks

README.md, src/stripe.core.ts, test/RequestSender.spec.ts, test/StripeResource.spec.ts, test/resources/Quotes.spec.js, test/stripe.spec.ts, test/testUtils.ts
Changes the default behavior of stripe-node to perform 1 reattempt on retryable failures by default, instead of 0. Retrying is generally safe. This is the same behavior as in `stripe-go`.
This will improve the default experience in environments like AWS Lambda where broken connections are inevitable (fixes #1040)
=> (next major) one network retry by default

src/Webhooks.ts, test/Webhook.spec.ts
Adding an error message that is surfaced when a signing secret that contains whitespace is used.
=> Adding error message for when signing secrets contain whitespace

types/FilesResource.d.ts, types/lib.d.ts, types/test/typescriptTest.ts
Adds type definition to `files.create()` method params.
=> Generate FileCreateParams

src/Webhooks.ts, src/crypto/CryptoProvider.ts, src/crypto/SubtleCryptoProvider.ts, test/Webhook.spec.ts
In response to #1827.
* I could have made a smaller change to just add the string to `SubtleCryptoProvider.computeHMACSignature` itself, but it felt wrong to me for `.computeHMACSignature` to make assumptions about how it was called, so instead I introduced a specialized error class for `constructEvent` can produce the message. Open to reversing this upon feedback.
* I didn't change the default implementation of `.computeHMACSignature` to throw this error. That means we're asking hypothetical implementors of additional async-only CryptoProviders will have to explicitly override `.computeHMACSignature` to throw this error instead of just only implementing `.computeHMACSignatureAsync`. This kind of is a bummer but I think it prevents misleading error messages in the hypothetical case where …
=> Better CryptoProvider error

test/resources/generated_examples_test.spec.js, test/testUtils.ts
File-returning methods pass `files.stripe.com` as a host so passing stripe-mock address into client constructor doesn't intercept them. A special HttpClient implementation does.
=> Intercept test calls that hardcode API base

CHANGELOG.md
Multiple users have run into the issue described in https://github.com/stripe/stripe-node/issues/1822 since our docs use `cancel`. We should call this out in the Changelog and guide users on versions prior to v9.14.0 to use `del` instead.
=> Call out addition of subscriptions.cancel in Changelog

src/net/NodeHttpClient.ts, test/StripeResource.spec.ts, tsconfig.cjs.json
Reverts stripe/stripe-node#1854
We should not use `esModuleInterop` because this is a breaking change
> Accordingly, library authors should set both allowSyntheticDefaultImports and esModuleInterop to false. This allows consumers to opt into these semantics, but does not require them to do so. Consumers can always safely use alternative import syntaxes (including falling back to require() and import()), or can enable these flags and opt into this behavior themselves.
https://www.semver-ts.org/#module-interop
Thank you for catching this @anniel-stripe!
=> Revert "import * as http -> import http from 'http'"

src/net/NodeHttpClient.ts, testProjects/mjs/index.js, tsconfig.cjs.json
Achieves a similar affect as https://github.com/stripe/stripe-node/pull/1854 (but without turning on the `esModuleInterop` option) to enable monkey patching of the 'http' / 'https' modules when importing stripe as an ES module.
Also adds a test to prevent against future regressions, and makes `esModuleInterop: false` explicit.
Motivation: https://github.com/stripe/stripe-node/issues/1844
=> Allow monkey patching http / https

types/lib.d.ts
The JSDoc of `maxNetworkRetries` had multiple issues including it still specified the default as 0 despite being upgrade to 1 in 13.0.0.
It also fixes the broken `Idempotency keys` link.
I also slightly reworded the description which I feel is more clear but that is of course subjective.
=> Improved `maxNetworkRetries` options JSDoc

test/resources/generated_examples_test.spec.js, types/Accounts.d.ts, types/AccountsResource.d.ts, types/BalanceTransactionSources.d.ts, types/BalanceTransactions.d.ts, types/CustomerSources.d.ts, types/CustomersResource.d.ts, types/ExternalAccounts.d.ts, types/PaymentIntents.d.ts, types/Payouts.d.ts, types/index.d.ts, types/shared.d.ts
We had a manually maintained `CustomerSource` union before but all other polymorphic types were expanded in-place.
=> Add named unions for all polymorphic types

README.md, examples/webhook-signing/express/main.ts, examples/webhook-signing/koa/main.ts, examples/webhook-signing/nestjs/app.controller.ts, examples/webhook-signing/nextjs/pages/api/webhooks.ts, examples/webhook-signing/test/main.ts, scripts/updateAPIVersion.js, testProjects/cloudflare-pages/functions/index.js, types/index.d.ts, types/lib.d.ts, types/test/typescriptTest.ts
Now that the library is pinned to the latest API version we can remove the requirement to pass the explicit version.
=> Do not require passing apiVersion

src/Webhooks.ts, src/stripe.core.ts, test/Webhook.spec.ts, testProjects/mjs/index.js, types/index.d.ts
See #1956 
`Stripe.webooks` has the following changes
- The `platformFunctions` parameter is now optional, defaulting to the `platformFunctions` instance used by the Stripe object
- It is now also confirms to the `Stripe.Webhooks` signature so that `Stripe.webhooks` can be used as a static reference to the webhook utilities
Furthermore, all `Stripe` instances share the same reference to the static `Stripe.webhooks` object/function.
The function signature will be removed as a breaking change in the next major release.
=> Move Webhooks instance to static field

types/EventTypes.d.ts
These events will be removed in an upcoming major version.
Motivation: https://github.com/stripe/stripe-node/issues/1984
=> Update docstrings to indicate removal of deprecated event types

src/stripe.core.ts, test/stripe.spec.ts
As suggested in #2006.
There is no analogous check in the other libraries (stripe-ruby, stripe-python), and the use case outlined in #2006 seems legitimate. Considering that setting the protocol to 'http' is something that users need to explicitly opt into anyway, throwing the exception here seems a little heavy-handed in the presence of legitimate use cases.
The existing test that asserted that an exception was thrown in this case failed. Then I removed it.
* Stops throwing exceptions if `protocol: 'http'` is set for requests to `api.stripe.com`.
=> Remove https check for *.stripe.com

src/resources/Accounts.ts, src/resources/Customers.ts, src/resources/Invoices.ts, types/AccountsResource.d.ts, types/ApplicationFeesResource.d.ts, types/CreditNotesResource.d.ts, types/CustomersResource.d.ts, types/Deprecations.d.ts, types/InvoicesResource.d.ts, types/SubscriptionItemsResource.d.ts, types/TransfersResource.d.ts, types/index.d.ts, types/shared.d.ts, types/test/typescriptTest.ts
Standardizes param class names to `<ResourceName><MethodName>Params`.
Adds type-forwards to preserve existing types.
=> Standardize parameter interface names

.vscode/settings.json
As of [VSCode v1.85](https://code.visualstudio.com/updates/v1_85#_code-actions-on-save-and-auto):
> the previous boolean values to be deprecated in favor of the string equivalent.
Discovered from https://stackoverflow.com/questions/77637621/vscode-workspace-settings-change-on-its-own because .vscode/settings kept changing on me
=> vscode settings: true -> "explicit"

types/BalanceTransactions.d.ts, types/Climate/Suppliers.d.ts, types/EventTypes.d.ts, types/Events.d.ts, types/InvoicesResource.d.ts, types/PaymentIntentsResource.d.ts, types/PaymentMethodConfigurations.d.ts, types/Reporting/ReportRunsResource.d.ts, types/SetupIntents.d.ts, types/TaxRates.d.ts, types/TaxRatesResource.d.ts, types/WebhookEndpointsResource.d.ts
This PR contains the changes generated after removing the shared overides from our code generator that were added for backcompat
* Remove the below deprecated values for the type `BalanceTransaction.Type`
* `obligation_inbound`
* `obligation_payout`
* `obligation_payout_failure`
* `'obligation_reversal_outbound'`
* Remove deprecated value `various` for the type `Climate.Supplier.RemovalPathway` 
* Remove deprecated events 
* `invoiceitem.updated`
* `order.created`
* `recipient.created`
* `recipient.deleted`
* `recipient.updated`
* `sku.created`
* `sku.deleted`
* `sku.updated`
* Remove types for the deprecated events 
* `InvoiceItemUpdatedEvent`
* `OrderCreatedEvent`
* `RecipientCreatedEvent`
* `RecipientDeletedEvent`
* `RecipientUpdatedEvent`
* `SKUCreatedEvent`
* `SKUDeletedEvent`
* …
=> Remove parts of the API that is no longer publicly documented

types/EventTypes.d.ts
The Created and Deleted events for Invoice Item have had wrong casing in stripe-node making them inconsistent with other event names. This PR fixes the casing to make them more intutive.
* Rename event type `InvoiceitemCreatedEvent` to `InvoiceItemCreatedEvent`
* Rename event type `InvoiceitemDeletedEvent` to `InvoiceItemDeletedEvent`
=> Fix casing on InvoiceItem related events

README.md
This change to the `README.md` file makes it more explicit that the `limit` value passed to `autoPagingToArray` is the limit for the total number of items that will be fetched from Stripe, and *not* a limit for the number of items retrieved per fetch during multiple rounds of fetching. The note about preventing runaway memory growth was suggestive of this behavior, but not entirely explicit.
=> Note on `limit` param in `autoPagingToArray`

types/ConfirmationTokens.d.ts, types/Issuing/AuthorizationsResource.d.ts, types/PaymentIntents.d.ts, types/PaymentIntentsResource.d.ts, types/PaymentMethods.d.ts, types/SetupIntents.d.ts, types/SetupIntentsResource.d.ts
This PR adds Node SDK support for automatically marking methods and params as deprecated. 
- Mark as deprecated the `approve` and `decline` methods on `Issuing.Authorization`. Instead, [respond directly to the webhook request to approve an authorization](https://stripe.com/docs/issuing/controls/real-time-authorizations#authorization-handling).
- Mark as deprecated the `persistent_token` property on `ConfirmationToken.PaymentMethodPreview.Link`, `PaymentIntent.PaymentMethodOptions.Link`, `PaymentIntentResource.PaymentMethodOptions.Link`, `PaymentMethod.Link.persistent_token`. `SetupIntents.PaymentMethodOptions.Card.Link.persistent_token`, `SetupIntentsResource.persistent_token`. This is a legacy parameter that no longer has any function.
=> Deprecate Node methods and params based on OpenAPI spec

Makefile
When running the node test suite, many tests passed but those dependent on `deno` and `stripe-mock` only failed after the rest of the test suite had run. 
For local development, it seems worthwhile to ensure those are running before running the whole suite.
Also, my understanding is `make test` is only run locally, so this PR won't affect CI (or anything besides us running `make test` on our laptops). If that's not the case, let me know!
=> add local pre-req script to bail early if tests will fail

types/PaymentIntentsResource.d.ts, types/PaymentMethodsResource.d.ts, types/SetupIntentsResource.d.ts
* Change type of `PaymentIntentConfirmParams.mandate_data` from `Stripe.Emptyable<PaymentIntentConfirmParams.MandateData1 | PaymentIntentConfirmParams.MandateData2>` to `Stripe.Emptyable<PaymentIntentConfirmParams.MandateData>` where the new MandateData is a union of all the properties of MandateData1 and MandateData2
* Change type of `PaymentMethodCreateParams.card` from `PaymentMethodCreateParams.Card1 | PaymentMethodCreateParams.Card2` to `PaymentMethodCreateParams.Card` where the new Card is a union of all the properties of Card1 and Card2
* Change type of `SetupIntentConfirmParams.mandate_data` from `Stripe.Emptyable<SetupIntentConfirmParams.MandateData1 | SetupIntentConfirmParams.MandateData2>` to `Stripe.Emptyable<SetupIntentConfirmParams.MandateData>` where the new MandateData is …
=> Where params are union of types, merge the types instead of having numbered suffixes in type names

testProjects/mjs-ts/index.ts
The latest API version means a different string literal when creating a client, causing a type error in a test. I've updated the test.
Long term we should set this up so new API versions don't break CI, but this is fine for now.
=> Update API version in TS example project

package.json
Add `bun` conditional exports target. Currently, Bun users who import Stripe get the default version of stripe-node, which produces errors if they don't configure Stripe with the `httpClient` option. Adding this target will allow Bun users to receive the web platform version of `stripe-node`.
https://github.com/stripe/stripe-node/pull/2090
=> Use worker module in Bun

testProjects/mjs-ts/index.ts
When releasing the most recent major, the types required a specific API version: 
https://github.com/stripe/stripe-node/blob/e219b05f02f09efb57b13e50977012d001a49223/types/lib.d.ts#L30
So this test was failing until we adjusted the string. A test that fails on a schedule isn't great and the test isn't verifying anything especially useful. I think it's more trouble than it's worth, so I pulled it.
=> Remove TS test that cares about a specific API version

.eslintrc.js, src/ResourceNamespace.ts, src/multipart.ts, src/stripe.core.ts
When using iterating over the properties of an object, we should be defensive and ensure we're only using the properties that belong directly to that object (not anything inherited from the prototype chain). If users have modified the base `Object`, then we'll modify _those_ modifications in a way we shouldn't, causing issues.
This seemed like something we could catch in lint, and it is! We just disabled the rule for some reason. So I re-enabled it and fixed the errors.
More info: https://eslint.org/docs/latest/rules/guard-for-in
---
Fixes #2114 
Fixes [RUN_DEVSDK-1209](https://jira.corp.stripe.com/browse/RUN_DEVSDK-1209)
=> check `hasOwnProperty` when using `for..in`

.github/workflows/main.yml, .mise.toml, examples/webhook-signing/.gitignore
Updates CI to test against the latest Node.js versions
Full list is here: https://nodejs.org/en/about/previous-releases
We should focus on the even-numbered releases, since those are (or will be) LTS.
Also:
- added `deno` to the local install so the full unit test suite passes
- added its lockfile to the gitignore
=> update node versions in CI

README.md, src/RequestSender.ts, src/Types.d.ts, src/stripe.core.ts, src/utils.ts, test/stripe.spec.ts, types/index.d.ts, types/lib.d.ts
Adds the ability to make raw requests to the Stripe API, by providing an HTTP method and url.
Example:
```node
import Stripe from 'stripe';
const stripe = new Stripe('sk_test_...');
const response = await stripe.rawRequest(
'POST',
'/v1/beta_endpoint',
{ param: 123 },
{ apiVersion: '2022-11-15; feature_beta=v3' }
);
```
=> Add raw_request

README.md, src/RequestSender.ts, src/Types.d.ts, src/stripe.core.ts, src/utils.ts, test/stripe.spec.ts, types/index.d.ts, types/lib.d.ts, types/test/typescriptTest.ts
Adds the ability to make requests to the Stripe API that are not directly supported in the SDK, by providing an HTTP method, url and relevant parameters
Example:
```node
import Stripe from 'stripe';
const stripe = new Stripe('sk_test_...');
const response = await stripe.rawRequest(
'POST',
'/v1/beta_endpoint',
{ param: 123 },
{ apiVersion: '2022-11-15; feature_beta=v3' }
);
```
=> Add raw request

types/ThinEvent.d.ts, types/V2/Core/EventsResource.d.ts
There were typing issues with the return value of `client.v2.core.events.list()`. Codegen originally produced `Stripe.V2.Event` but it wasn't able to find that type, despite it being exported. Ramya manually changed the value to `Event`, which being in the `V2` namespace already, picked the correct one. But, we wanted the codegen output to be correct. 
There was also an issue with `ApiListPromise`. It was pulled from the V2 types so I decided to use the V1 type instead. They're very similar and users won't be interacting directly with them, we think.
- codegens a `<reference path='../EventTypes.d.ts' />` to make `V2.Events` explicitly available
- manually changes the shape of the `relatedObject` interface to not nest the data. Without that change, I had to reference relatedObject as …
=> Fix typing of `Stripe.V2.Event`

src/autoPagination.ts
The API will error if we send these params twice (once from requestArgs and once from the returned nextPageUrl).
The firstPagePromise will contain the params, which will be passed through with nextPageUrl.
=> Remove parameters sent as part of additional autoPaginatingEach calls in v2

src/stripe.core.ts, types/index.d.ts
We already have `stripe.webhooks.constructEvent` available, and we believe that we may want to unify thin and snapshot event processing on Stripe eventually. Thus, parseSnapshotEvent is not actually useful to add for users.
=> Remove parseSnapshotEvent

CHANGELOG.md, README.md
When we merged from master to beta yesterday, we should have used our merge script and then NOT used the squash option when merging the PR as this results in future merges by the automation to not know how to resolve certain merge conflicts.
This PR has the changes from running our merge script and resolving the resulting merge conflicts.
Note: DO NOT use the squash option when merging
=> Merge into beta using the merge script

types/V2/Billing/MeterEventAdjustments.d.ts, types/V2/Billing/MeterEventSessions.d.ts, types/V2/Billing/MeterEvents.d.ts
CI failures are expected because stripe-mock doesn't yet have the changes these this PR is responding to
- fixes a bug where the `object` property of the `MeterEvent`, `MeterEventAdjustment`, and `MeterEventSession` didn't match the server.
=> update object tags for meter-related classes

scripts/updateAPIVersion.js, types/lib.d.ts, types/test/typescriptTest.ts
1. Updated the API version regex in the `updateApiVersion,.js` script to handle new format of API versions(eg. `2024-09-30.acacia`). This script is run every time we run `codegen-format`.
2. Cleanup of lines that tried to update API version in files(Readme and package.json) that no longer reference an API Version.
=> Updated API version in types/lib.d.ts

README.md
fixes https://github.com/stripe/stripe-node/issues/2207 by adding more information to the README
=> add missing key warning to README

.editorconfig, .eslintrc.js, .github/workflows/main.yml, .prettierignore, Makefile, README.md, examples/webhook-signing/prepare.sh, justfile, package.json, scripts/updateAPIVersion.js, test/Integration.spec.ts, yarn.lock
In an effort to modernize and simplify our local tooling, we're moving our dev commands from makefiles to [justfiles](https://github.com/casey/just). This is intended to be mostly a drop-in replacement, but some command names may change per standardization efforts.
To be in line with our other SDKs, I removed most of the scripts in `package.json`. But, if we find that potential contributors are having trouble with muscle memory, we can re-add common ones (`test`, `lint`, etc) that call into `just`.
In order to untangle formatting and linting (which [Prettier recommends](https://prettier.io/docs/en/integrating-with-linters.html#notes) keeping separate, I removed `plugin:prettier` from the eslint config. This mean the formatting-related lint rules are disabled, deferring to `prettier` …
=> add justfile, remove coveralls, tweak ESLint

.npmignore
Currently, there's no way to trace back the openapi version to the generated client, since only `VERSION` is included, but not `OPENAPI_VERSION`.
When downloading the spec via `https://raw.githubusercontent.com/stripe/openapi/refs/tags/<OPENAPI_VERSION>/openapi/spec3.json`, `OPENAPI_VERSION` is required since versioning is not done using any other version value like `2024-12-18.acacia`.
Having the file there would easily allow for a file read and access the right used version at runtime :)
This PR simply as [OPENAPI_VERSION](https://github.com/stripe/stripe-node/blob/master/OPENAPI_VERSION) into npm package contents.
=> Include `OPENAPI_VERSION` into npm bundle

examples/webhook-signing/nextjs/app/api/webhooks/route.ts
Adds an example [Route Handler](https://nextjs.org/docs/app/building-your-application/routing/route-handlers) for handling webhook events in Next.js App Router projects.
Mostly a copy/paste from the example I added to the [Next.js repo](https://github.com/vercel/next.js/blob/canary/examples/with-stripe-typescript/app/api/webhooks/route.ts).
=> Add Next.js App Router webhook example that leverages Route Handlers

.github/workflows/main.yml
CI is failing since last week as v2 of actions/cache is deprecated 
Upgrade actions/cache to v4
https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
=> Update actions/cache as v2 is deprecated

src/stripe.core.ts
In https://github.com/stripe/stripe-node/issues/1956, a user flagged that they wanted to be able to use webhook utilities before creating a `Stripe` instance. Since the webhook utilities were standalone (didn't depend on anything inside `Stripe`) we made them static. But because they were factory functions before, we didn't want to break that mid-cycle. Now that it's time for a major version, we can complete this change.
- set `Stripe.webhooks` to the result of `createWebhooks()` directly
- set `this.webhooks` inside the `Stripe` constructor to the value at `Stripe.webhooks`
- [DEVSDK-1702](https://go/j/DEVSDK-1702)
- https://github.com/stripe/stripe-node/issues/1956
- ❗ `Stripe.webhooks` and `Stripe().webhooks` are no longer functions (just plain objects)
- if you were calling …
=> [BREAKING] swap Stripe.webhooks from a factory function to a static property

test/resources/SubscriptionItems.spec.js
There are a lot of endpoints being (re)moved in the upcoming GA release. This remove manually maintained tests that reference these endpoints.
Removes tests for UsageRecord and UsageRecordSummary
=> Remove tests for endpoints that were removed

types/Deprecations.d.ts, types/test/typescriptTest.ts
We had some manually maintained types that reference types that have now been removed, failing the build.
- removed unavailable types
- update test to use a still-present deprecated type
=> remove type checks for removed endpoints

types/lib.d.ts
Some v2 APIs have the v2 `Amount` shape now, but that interface only existed in the private beta repos. This copies that interface over to clear CI failures.
- copy `Amount` interface
- [DEVSDK-1265](https://go/j/DEVSDK-1265)
=> add Amount interface

types/V2/EventTypes.d.ts
Manually creating PRs as automation is currently failing
Re-generating after the latest set of fixes in the codegen around fixing event names and related objects
Re-run code gen
=> Fix event names and related objects

CHANGELOG.md
Fixing the link in the changelog from acacia to basil
=> Update CHANGELOG.md to use the right release train

types/ExternalAccountsResource.d.ts
The `external_account` field should be a union type, not a `string`.
- Changes `external_account` field in `ExternalAccountsCreateParams` from a `string` to a union type.
- Changes `external_account` field in `ExternalAccountsCreateParams` from a `string` to a union type.
=> Handle external_resource field

.github/workflows/main.yml
Node sub dependency(eslint-util) added optional chaining which isn't supported in Node 12.
Removed 12 tests from CI.
https://jira.corp.stripe.com/browse/RUN_DEVSDK-1610
=> Remove Node 12 from CI

.github/workflows/main.yml
This reverts commit 23739dbcae6dbfd81567b9bbbfd7b3f0b3149c50.
Adding this back in, and will be skipping the integration linting test. 
https://jira.corp.stripe.com/browse/RUN_DEVSDK-1610?focusedId=20826574&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-20826574
Reverted removal of node 12 changes
=> Revert "Remove Node 12 from CI (#2306)"

src/RequestSender.ts, src/StripeResource.ts, src/utils.ts, test/RequestSender.spec.ts, test/StripeResource.spec.ts, test/utils.spec.ts
Host and streaming option when passed through raw request are not honored while making the actual request.
- Host and streaming are now settable when passed as request options when making a raw request.
https://jira.corp.stripe.com/browse/RUN_DEVSDK-1525
* RawRequest now allows you set `host` and `streaming` in request options. Eg.
```typescript
const file = await stripe.rawRequest(
'GET',
'/v1/files/file_123/contents',
{},
{host: 'files.stripe.com', streaming: true}
);
```
=> RawRequest can use custom host

.mise.toml
Before, we were piggybacking our local node version on another internal project that happened to also use node. We should declare this project's dependencies explicitly.
- add explicit node version to mise
=> add mise config for node version

test/resources/generated_examples_test.spec.js, types/V2/Payments/OffSessionPayments.d.ts, types/V2/Payments/OffSessionPaymentsResource.d.ts
Changes were done to OffSessionPayment API in the May release which did not make it to the SDKs. Pulling those changes in now and making another SDK release for the `2025-05-28.preview` API version
- Pull protos in codegen for `2025-05-28.preview`
- Generate the SDK
=> Pull in OffSessionPayment changes for the May release

src/stripe.core.ts, types/lib.d.ts
A [user requested](https://github.com/stripe/stripe-node/issues/2357) that Stripe class should export the API_VERSION. 
- Export `API_VERSION` on non-instantiated Stripe class. 
https://github.com/stripe/stripe-node/issues/2357
* Use `API_VERSION` on `Stripe` class to access API version pinned to the current SDK.
```typescript
import { Stripe } from "stripe";
console.log(Stripe.API_VERSION);  // 2025-06-30.basil
```
=> Export API_Version string in Stripe class

examples/snippets/meter_event_stream.ts
I didn't find any place where it's referenced that expires_at is in seconds.
=> fix(example): expires_at is in milliseconds

src/apiVersion.ts, types/lib.d.ts, types/test/typescriptTest.ts
The Open API spec used to generate the SDK was using an older API version. The spec with the fix for this cannot be used as it also contains changes meant for the next release. Therefore, manually making the API version change here
Update API version 2025-08-04.private to 2025-08-27.preview
=> Use the right API version 2025-08-27.preview

.github/workflows/main.yml, README.md
When you release on NPM, you can specify a tag for the release ([docs](https://docs.npmjs.com/cli/v11/commands/npm-dist-tag)). This lets your users install an alias that points to the latest release in a channel:
```
npm install package@whatever
```
Previously, we've tagged everything that wasn't GA with the `beta` tag. That has two issues:
1. Now that there's private-preview releases, not all non-GA releases are "beta"
2. We're moving away from the `beta` nomenclature in favor of `public-preview`
To support this change, we updated the tags we use when publishing. These tags can be any string, so switching them is fine. There's nothing special about the `beta` tag we were using.
The only downside is that for new users who find docs that still say `npm install stripe@beta`, they'll now get …
=> support more npm tags

src/net/FetchHttpClient.ts
Merging https://github.com/stripe/stripe-node/pull/2167 introduced a bug in Bun runtimes. Although we don't officially support Bun today, this PR fixes a user reported issue [#2416](https://github.com/stripe/stripe-node/issues/2416)
Undo JSON.stringifying object bodies in Bun. 
* ⚠️ Fixed issue with file uploads in runtimes using `FetchHttpClient` (e.g. Bun). This bug affected Node SDK versions between 18.1.0 to 18.5.0.
=> Fixed file uploading in Bun runtimes

.github/workflows/main.yml, CHANGELOG.md, README.md
We're using a different `pref` name in the docs for the version deprecation policy, so these links need to be updated.
- replace `?server=` with `?lang=` in links
=> Update param in deprecation docs link

.github/workflows/main.yml
We added some debug logging in https://github.com/stripe/stripe-node/pull/2437 https://github.com/stripe/stripe-node/pull/2439. Now that the script is working, we don't need them anymore!
- removed extra `cat` calls
- set pipefail on the script
=> cleanup logging in publish job

CHANGELOG.md
- Entries for the mid month Sept release were not language specific diffs. Fixed that
- Changes to v1 APIs in private preview were missing from the changelog. Added those
- 3 dispute related events were suppressed from sdks but are appearing in the changelog. Removed those
=> Update changelog for private preview
